### ISSUE TITLE
(Client): Display all allocated EW and Fire

### ISSUE THREAD

**Issue by Aatu** [Aatu/FieryVoid#10]
1 . Button or hotkey which will display ALL EW (Same as when hovering over a ship, but for all ships). 
1. Similiar system for Firing orders displaying which ship is targeting which. Lines should use same color as animations (weapon.animationColor).

**Comment by Zero1627** [comment]
this is done? hotkeys 'e' (enemy) and 'w' (own) EW, and on mouseover shows EW relevant to a particular unit...
