### ISSUE TITLE
(Client & Server): Weapons that have limited and different ammunition (missiles)

### ISSUE THREAD

**Issue by Aatu** [Aatu/FieryVoid#12]
Needs:
- A table to database how much and what kind of ammo a weapon has
- Column to loading table (or power management) for what type of ammo is being loaded. Can use power management orders to track changes.
- UI buttons for changing ammo and graphics to displaying what is being loaded

**Comment by Zero1627** [comment]
I do have an idea how to do this. It would require my idea of ship upgrades to work first, though! - so it's definitely for laters.

**Comment by Zero1627** [comment]
there is a separate thread for that now, closing...
