### ISSUE TITLE
(Client & Server): Hyperspace

### ISSUE THREAD

**Issue by Aatu** [Aatu/FieryVoid#13]
- Jumping in and out
  - Using jump engine to start opening a jump point
  - Clicking on the system and choosing a command form opening menu?
  - Player chooses the hex where to open the jump point or the point is always opened on the same hex as the ship?
  - What orders does this use? Need new order type?
- Being in hyperspace
- Boolean variable to movement orders?

**Comment by Zero1627** [comment]
scenario oriented, pointless ATM.
