### ISSUE TITLE
HitLocation rewrite

### ISSUE THREAD

**Issue by AncientSion** [Aatu/FieryVoid#130]
In regards to finish rewriting the getHitSystem function, i require new "adjusted" SCS for non-capitals.

i need
1 each MCV, HCV, Cap from DRAZI faction,
1 each MCV, HCV from non-drazi faction,
1 misc OSAT.

Also, need to remember that the hitTable needs to contain the systems displayName.
Can you please issue one pull request for that lot ?

thanks

**Comment by tksolway** [comment]
Sure thing, I'll try and get this to you by the end of the day.
