### ISSUE TITLE
highlight Pivoting state

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#1312]
Would it be possible to make the Pivoting, Rolled and Rolling notations a different color than white? Something like magenta or yellow?
And if a ship is pivoting, is it possible to add which direction (CW or CCW)?

**Comment by melkorium** [comment]
This might be completed, with the new text tooltips I've added to Movement Icons.

**Comment by melkorium** [comment]
Closing due to tooltips added.
