### ISSUE TITLE
HitLocation again

### ISSUE THREAD

**Issue by AncientSion** [Aatu/FieryVoid#132]
Can you take a look on this, Tom ?
I know you arent "into" FV code per se, but most things should make sense regardless if you know the syntax, which you do. 

Is there anything missing in here in regards to how a system is designated for a capital, according to your interpretation ?
I can add in comments if it helps.

        public function getHitSystemByTable($pos, $shooter, $fire, $weapon, $location){
            $system = null;
            $name = false;
            
            if ($fire->calledid != -1)
                $system = $this->getSystemById($fire->calledid);
            
            if ($system != null && !$system->isDestroyed())
                return $system;
        
            if ($location === null)
                $location = $this->getHitSection($pos, $shooter, $fire->turn, $weapon);

            $hitChart = $this->hitChart[$location];
            $roll = mt_rand(1, 20);
            debug::log("roll: ".$roll." on loc: ".$location);

            if (isset($this->hitChart[$location][$roll])){
                $name = $this->hitChart[$location][$roll];
                debug::log("name: ".$name);
            }
            else {
                debug::log("no name for that roll -> while");
                while (!$name){
                    $roll++;
                    if (isset($hitChart[$roll])){
                        $name = $hitChart[$roll];
                        debug::log("WHILE name: ".$name);
                    }
                }
            }

            if ($name == "primary"){
                debug::log("redirecting to PRIMARY");
                $name = false;
                $location = 0;
                $roll = mt_rand(1, 20);
            debug::log("NEW roll: ".$roll." on loc: ".$location);

            if (isset($this->hitChart[$location][$roll])){
                    $name = $this->hitChart[$location][$roll];
                    debug::log("name: ".$name);
                }
                else {
                    debug::log("no name for that roll -> while");
                    while (!$name){
                        $roll++;
                        if (isset($this->hitChart[$location][$roll])){
                            $name = $this->hitChart[$location][$roll];
                            debug::log("WHILE name: ".$name);
                        }
                    }
                }
            }

            debug::log("hitLoc: ".$location.", hitting: ".$name);

            $systems = array();

            if ($weapon->flashDamage){
                foreach ($this->systems as $system){
                    if ($system->location == $location && !$system->isDestroyed() && !$system instanceof Structure){
                        $systems[] = $system;
                    }
                }
            }
            else {
                foreach ($this->systems as $system){
                    if ($system->location == $location){
                        if ($system->name == $name){
                            if (!$system->isDestroyed()){
                                $systems[] = $system;
                            }
                        }
                    }
                }
            }

            if (sizeof($systems) > 0){
                $roll = mt_rand(1, sizeof($systems));
                $system = $systems[$roll-1];
                debug::log("target systems: ".sizeof($systems).", rolled: ".$roll.", hitting: ".$system->displayName);
                return $system;
            }
            else {

                $system = $this->getStructureSystem($location);
                debug::log("systems <= 0, checking for structure of location ".$location);

                if ($system->isDestroyed()){
                    debug::log("structure destroyed");
                    if ($location != 0){
                        debug::log("but not 0");
                        if($system->isDestroyed($fire->turn -1)){
                            debug::log("destroyed last turn, get hitsystem on loc 0");
                            $this->getHitSystem($pos, $shooter, $fire, $weapon, 0);
                        }
                        else {
                            debug::log("destroyed this turn");
                            $system = $this->getStructureSystem(0);
                            debug::log("got structure 0");
                            if ($system->isDestroyed()){
                            debug::log("is destroyed, return null");
                                return null;
                            }
                            else { 
                            debug::log("alive, returning prim sturcture");
                                return $system;
                            }
                        }
                    }
                }
            }
        }

**Comment by tksolway** [comment]
Major issue I see,
    if (isset($this->hitChart[$location][$roll])){
            $name = $this->hitChart[$location][$roll];
            debug::log("name: ".$name);

You set hitchart to the subarray related to the hit location ( $hitChart = $this->hitChart[$location];)

But then this if attempts to access a sub array of the sub array.  I assume you are getting exceptions thrown because the memory location doesn't exist.  

Should be:
    if (isset($this->hitChart[$roll])){
            $name = $this->hitChart[$roll];
            debug::log("name: ".$name);

**Comment by tksolway** [comment]
Looks like that will need to be changed in a couple more ifs as well

**Comment by tksolway** [comment]
Another way to fix it is just change 
$hitChart = $this->hitChart[$location];

to 
$hitChart - $this->hitChart;

I think, sometimes assigning arrays to values like this doesn't work as expected.  Haven't played around with it too much in PHP.

**Comment by tksolway** [comment]
On second thought, this might be overriding the $hitchart related to the object, perhaps this:

$tempChart = $this->hitChart[$location];

Then 

if (isset($tempChart[$roll])){
$name = $tempChart[$roll];
debug::log("name: ".$name);

**Comment by AncientSion** [comment]
Oops, thats a relic. The $hitChart variable is NOT used anymore at all, the *entire* code is now referecing $this->hitTable instead of the $hitChart variable. The line is not used at all...

I did some shooting and it worked okay.
My main problem is 
1. How does Flash damage work into this equation
2. How does this function need to be altered if its part of the HCV or MCV class compared to the capital-ship class.

Like, if i use a flash weapon versus an MCV, do i roll for ENTIRE hitChart of the MCV or just for front or aft depending in axis ? And what happens if my weapon i.e. destroys all systems on the front, where do i overkill into ?

**Comment by AncientSion** [comment]
Do you by accident have a server (phys or virtual) running in the net ?

**Comment by tksolway** [comment]
I don't think you will have to alter the function at all to handle other sized ships.  If you can trust the gethitsection to never return a non-existent section, then regardless of which facings exist or not you should always have an array to access.  It's really the gethitsection function that needs to worry about the ship layout. 

For flash damage you really just have to remove primary from the equation until it needs to be added.  
Algorithm:
-Roll d20
-Check table
  -If roll is primary
    -check if non-destroyed system remains in section
       -if yes - roll again
       -else proceed to roll on primary

Otherwise, flash would work as it does now with the damage allocation and then calling for a new hitsystem.  One other thing to remember with flash, is if you roll thruster and no thursters exist un-destroyed, it doesn't not go directly to structure, it rolls again on the table.  However, if you roll structure on the table, then the damage goes to structure.  

I don't have a server up yet, sorry, I'm currently moving to a new job, so I likely won't be able to get that stuff up and running for a few weeks.

**Comment by tksolway** [comment]
You only have to worry about the targeted facing for Flash.  Medium ships have their structure targeted in their fore or aft hit charts anyway, so flash damage will never penetrate to primary, it will destroy the ship first.  on HCVs you will have to completely eliminate all boxes on the targeted section, but afterwards you roll on the primary using the same rules as you used to roll for the fore or aft sections (although you never have to worry about ignoring a primary hit since they don't exist in the primary hit chart).

**Comment by tksolway** [comment]
Have you created a branch for this?  I can sync that branch and take a look at the code directly in my IDE
