### ISSUE TITLE
Vree

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#141]
AncientSion, since you've figured out the bases, does this mean the engine now supports the Vree facings?  they still have a couple weapons and Turrets that we would need to figure out.  But is there any reason why their ships facings would not be supported now?

**Comment by AncientSion** [comment]
Firstly, Chris, please, regardless of "where".

The way bases work is that are kinda in a permanent, continues pivot. Im not sure how exactly that translates to Vree. 
In fact, i probably dont know half of the "new" rules, even though we talked about them on FB in past.

If you could walk me through the things that are "different" from normal ships (anything really), i would be really helpful. That way i could think about it, write some notes in this thread etc. Also, there would be permanent place for them here, instead of the wacky FB chat.

Note that my initial thoughts about whats next were either Shadows or Vorlons. The information about Vree would be useful regardless and depending on the actual information, i may change even change my plan.

**Comment by tksolway** [comment]
Not a problem, I like having these sorts of discussions here anyway.  

The biggest issue with the Vree is that most of their ships are divided into 6 facings, much like a base, with each facing have a 60deg arc.  

that being said, they also have turrets.  The weapons in the turret generally have a 360deg arc, but all weapons in a turret must fire in the same 60deg arc during each turn.

They also have antimatter weapons, these use the to hit roll as a modifier to their damage, so if you roll a 15 when you needed a 16 to hit you don't do as much damage as if you rolled a 6.  Basically X is 1 and 10 in these two instances (needed - hit roll) and most anti matter weapons are something like: "do 4x dmg".

Their special weapon the Shredder also targets a hex rather than a specific ship, doing a random number of hits based upon the size of the targets in that hex.  

That's all the special stuff I can think of off the top of my head.  There's definitely some work there, but if your work on bases can be translated to the Vree ship design then that's a good start.  

I seem to remember the Vree being very popular.

**Comment by AncientSion** [comment]
Taking a look at the SCS, HCVs and Caps have 2 side sections each, so they basicly use the exact same shipwindow that bases will.

From your description, the following things would require work, everything else is done
- thinking up a way to display a weapon turret that is in-style with how the ship window looks
- thinking up a way to bind a thruster to more than one location (all non-mcv vree seem to have their side thrusters tied to both locations)
- thinking up a way to bind turret-mounted weapons each other (within the arc of the first weapo fired).
- Shredder (easy).
- I think you are missing something about their turrets. There are turrets in the primary, which hold 2 weapons with armour and HP, but the hit table doesnt list them, nor the framing turret. So i guess there is more still to turrets ?


I cant see anything remotely "difficult" at this point. The most time-consuming part would probably be to set up something interface-wise that makes turrets "easy" to use while also fitting the style / visuals of the shipwindow.

Before you joined, there was a discussion on Vree. I think the majority of participants agreed that Vree are overpowered (as far as "i havent won against Vree, ever")., which might explain the "popular".

I think there were suggestions on how to adjust them that didnt raise opposition at all, dont remember what though.

Considering how we are planning to revert things i spend time on to implement (both recently as well as way back), i wont commit any time unless there is a clear consensus on the WHAT though.
Also, considering my frustation with certain, skewed, matchups, i am unwilling to work towards adding Vree in their (apparently) overpowered state.

**Comment by tksolway** [comment]
I believe that the turrets can be hit from all directions.  I will need to check my Militaries of the League to confirm when I get home though.  I can't seem to find the specific rule in the KS.  As far as I understand, when you roll a "weapon" hit from any direction then the turret weapon is a valid target for that roll.  turret's themselves don't take damage, but when you roll a crit on any weapon in a turret you also a roll a crit (unmodified by dmg) on the turret.  on a 17-20 that turret is now locked in the 60deg arc it last fired in for the rest of the scenario.  

We may have to build some sort of container to hold systems that would represent the turret.  That way we could apply the arc limits and determine if crits on the container need to be rolled etc.  

If you notice, the thrusters, and everything else, actually have arc readouts next to them as well.  If I remember correctly this is the arc that those thrusters can be hit from, unfortunately it does not correspond with the actual layout arcs.  So you can actually hit the front thruster from the side.

The more I think about it, the more I think we might have to build a special function for determining hit location on the Vree.  something like this:

-determine file direction As normal
-Take arc from fire direction
-check for structure existence in that arc (some structures overlap arcs, and I believe that all structure in that arc needs to be destroyed before you hit primary, need to check this though).
-if destroyed move to primary - roll on Primary chart - dmg primary system
-else roll on chart
-then look for system in arc of fire corresponding to roll -dmg system
-else - dmg structure

I'm going to need to check some stuff in the rules, because as I think this through I'm coming up with more questions for myself, but I'll clarify this all later when I have the book in hand.

**Comment by Zero1627** [comment]
I believe Tom got it essentially right. KitchenSink does not contain any reference to B5Wars ships or races, so there are no Vree there. But The rules themselves can be found: 
>5.7.1 Weapon Turrets

(just like Dilgar Pentacans can be found as 'Inverted-V Formation' ;) )


But there is one 'minor' additional detail (the one that makes Vree unbelievably resistant to Raking weapons). I can't find it in KS (which doesn't mean it's not there, I couldn't find Pentacans either...), but remember it clearly from B5Wars.net PBEM tournament when I faced Vree.

Normal units must assign all fire incoming from one unit to the same structure block.
Vree allocate any _LOCATION ROLL_ (which means every rake, too) to any appropriate instance that has firing source in arc... so 'Weapon' on Vree capital ship may mean any weapon on 2 or 3 outer sections, as well as the turret. What's worse, the 'Structure' is not exception... So Vree ships are impossibly resistant to attempts of system stripping - and even if systems are stripped, their raw Structure remains very resistant.
Won't do much vs Standard mode weapons though -  PulseCannons,  Bolters or Plasma Cannons remain just as effective as usual :)


Tom, please check in appropriate source book - I haven't actually seen the rule, above is as it was explained to me during that tournament.

**Comment by tksolway** [comment]
I seem to remember something about that too Chris.  I have the books at home so I’ll clear it up tonight or this weekend.  It’s always annoying that the Militaries of the League 1 is pretty much the only source book that doesn’t exist online ☺  That and the Dilgar anyway.

**Comment by Zero1627** [comment]
>all non-mcv vree seem to have their side thrusters tied to both locations

that's one more thing: If I remember correctly, 'outside' is essentially one location for Vree... Any outside system is attached to AT LEAST the sections it has in arc (possibly to all sections - so any system falls off only if ALL outer structure blocks are destroyed). This is vague memory however (I didn't destroy all that many Vree ship sections, so this didn't come to focus), needs check.

I don't remember any special movement-related rules for vree, though. They do pivot for free, but no special rule is needed for that. Specifically I do not remember any constant spinning, and pivot penalty to weapon fire is AFAIK in place.

>They also have antimatter weapons, these use the to hit roll as a modifier to their damage

Anti-Matter Converters are already implemented in FV (using X factor, even if not Max X), so this doesn't seem to be a serious obstacle.  I don't think there will be any serious difficulties with implementing range brackets and different no-lock-on-penalty , too.
The most difficult weapon seems Shredder - direct fire weapon being fired at a hex, which I believe is new. Also it's a combination weapon, with AMCannon as alternate firing mode.

But - I think their way of damage allocation is both most difficult and most important for their uniqueness.

Btw, sorry for commenting in Your thread - just saw something seemingly interesting in my mail and decided to comment ;)

**Comment by AncientSion** [comment]
This thread doesnt belong to anyone.

**Comment by tksolway** [comment]
To make it easy for everyone, here is the relevant excerpt from League1:

When a vree ship takes damage, there is only one hit location chart (labeled "General hits"), instead of the usual forward, aft and side hit lists.  All hits, regardless of direction roll on the general hits chart first.  The roll indicates what type of system was hit (usually thruster, weapon or structure), and the vree player is free to choose which system within that category to mark the damage on - provided that system faces the incoming weapons fire.  To determine this, consult the arc display next to each system on the vree ship control sheet.  (even structure blocks have these arcs).  If the incoming fire or damage is coming from the displayed direction, then it can be selected; otherwise it cannot be hit.  Note that systems on turrets are not considered primary hits, but are eligible to accept general damage (which means they can be hit from anywhere because of their 360arc TKS).  If not eligible system exists then it passes to structure as normal, and if no eligible structure exists it is applied to the primary structure as with any ship.  
In the case of structure blocks, and only structure blocks, only one such block can be hit during a single volley.  The vree player chooses which structure block to use the first time it is rolled in a volley.  No other block can be used that volley, any additional would penetrate to primary structure.  However subsequent volleys may be applied to other structure blocks.  
Due to the integrated construction of the saucer hull, the loss of structure blocks does not affecgt weapons and other systems located theron.  Thus, the destruction of external structure blocks does not result in any damage to any other systems.

**Comment by tksolway** [comment]
Basically this means we only have a single section other than primary, and all systems within that section are valid targets as long as their arc is valid based upon the direction of incoming fire.  I was also wrong about the turret critical, it locks the turret to the 60deg front arc of the ship. 

The way we could implement this is to roll on the chart and then cycle through all valid systems looking for a valid hit.  If more than one exists we choose the system with the most remaining structure (perhaps we always choose turret weapons last since they are generally the most valuable).  If no valid hits exist we cycle through structure looking for a valid hit either choosing the best structure block, or finally moving to primary structure.  The only caveat is we would need to track structure usage per volley so we don't spread damage across multiple structure blocks.

**Comment by Zero1627** [comment]
>In the case of structure blocks, and only structure blocks, only one such block can be hit during a single volley.

thankfully! so my memory was wrong here :) . I do not remember 'volley' definition though - is it all damage done by a single weapon? If so, player can't split Raking (or Pulse) weapon amongst multiple Structures, but may split multipe weapons.

>Due to the integrated construction of the saucer hull, the loss of structure blocks does not affecgt weapons and other systems located theron. Thus, the destruction of external structure blocks does not result in any damage to any other systems.

so, external systems do not fall off...

**Comment by tksolway** [comment]
Im 90% sure that volley is per weapon. So yes. You cant split raking. But two different raking weapons could be split.

The systems not falling off part means the outer section will almost never be destroyed before the primary structure goes byby. Woulf be interesting to play.

Thanks,
Thomas Solway B.Sc.

On Jan 16, 2016, at 12:02 AM, Zero1627 <notifications@github.com<mailto:notifications@github.com>> wrote:


In the case of structure blocks, and only structure blocks, only one such block can be hit during a single volley.

thankfully! so my memory was wrong here :) . I do not remember 'volley' definition though - is it all damage done by a single weapon? If so, player can't split Raking (or Pulse) weapon amongst multiple Structures, but may split multipe weapons.

Due to the integrated construction of the saucer hull, the loss of structure blocks does not affecgt weapons and other systems located theron. Thus, the destruction of external structure blocks does not result in any damage to any other systems.

so, external systems do not fall off...

-

**Comment by Zero1627** [comment]
currently under development by Douglas.
