### ISSUE TITLE
Mine launcher -> Motenai deployment

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#1415]
Abbai mine launcher - could be made as hex-targeted weapon, which then re-targets on nearest opponent within a given range? Not _quite_ a mine, but far better at keeping flavor than a missile launcher!

**Comment by Zero1627** [comment]
low priority though, I think

**Comment by melkorium** [comment]
Can now be done, most of the Abbai mine types can be made (even if they are expensive and not very good!).  Mine Launcher is just KL Ballistic Mine Launcher with shorter range I think.

**Comment by Zero1627** [comment]
Douglas made it!!!!
Good job!

Now awaiting actual Motenai deployment :)

**Comment by melkorium** [comment]
This is done, I just can't close Issue  :)
