### ISSUE TITLE
Yolu

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#142]
I'm doing the hit charts for the Yolu,  I noticed that some Yolu have a mix of Thrusters and Gravitic Thrusters, are there any reasons for this or is it just an oversight?  Perhaps this is causing some of the weird thrust related issues that have been reported.  

Some Yolu ships require quite a bit of love, they are significantly deviated from the SCS.

**Comment by AncientSion** [comment]
There is no reason for it. Per se, the only difference between a Thruster and a Gravitic Thruster is that the latter will ignore the first critical.
The whole advanced logic when it comes to turning etc is controlled over the $ship->gravitic variable, which all yolu ships should have.

In general, Yolu were rushed and we fixed SCS like half a douzen times already. I want to make sure the future holds proper SCS in the first place :dancer: 
You fixing them up is a good thing, thanks.
