### ISSUE TITLE
hit sections and ship fire order

### ISSUE THREAD

**Issue by AncientSion** [Aatu/FieryVoid#145]
Due to the recent talk, i did rearrange the order in which weapons fire resolve from the current system to how B5Wars envisioned it (ship by ship etc).
Also, i did alter the "decide where to aply hits to" to check once per shooter instead of once per shot.
Also, once my ongoing skirmishes are done, i will reorder weapon solution so that raking weapons resolve almost at the end of the chain - just like it was in practice in the board game.

Basicly, anything fire should then, if not already now, practicly work how B5Wars decided it should be (15 years ago, mind you).
These are my concessions to you guys.

In the same vain i will then declare my withdrawal from FV.
As a heads-up.

**Comment by tksolway** [comment]
Thanks Chris.  You've done amazing work for this game.  Hopefully I can continue to build on it.  Although I'm going to admit that I'll never come close to your productivity :-)

**Comment by Zero1627** [comment]
thanks Chris... You did A LOT. And if You ever feel like coming back, I hope You will :)

Also, I do hope You won't go too far away, our battles I ejoyed a lot!

**Comment by tksolway** [comment]
Tested this with the new pick location code you wrote, seems to work perfectly.
