### ISSUE TITLE
dynamic tiers?

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#1503]
perhaps make tiers visible - BUT also make them dynamic?
Eg. allow every player to vote online where a given faction belongs. Vox populi then decides!

Perhaps even allow to vote on commentaries as well (eg. Warlock makes them Superior) - and show commentaries if minimum number of votes is cast for them (eg. 50%)

**Comment by melkorium** [comment]
Just to say I lol'd at 'vox pupuli' :D

**Comment by Zero1627** [comment]
For now - closing the issue,, I think it's not needed.
