### ISSUE TITLE
Antoph HitChart

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#157]
Gravitic or Graviton pulsar, Hitchart typo.

**Comment by Zero1627** [comment]
I will take care of this, hopefully tomorrow.

**Comment by tksolway** [comment]
Great,

Thanks Zero, github is pretty good about having email replies go where you think they will.

**Comment by Zero1627** [comment]
I did appropriate correction. Also, I did a general review of Brakiri hit charts, and corrected a few. Tom, You might want to publish this update soon - among corrected units are Ikorta and Halik :)
