### ISSUE TITLE
EP Gun and SHF

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#158]
It was reported (and it seems so in log) that EP Gun hit caused instant-dropout on Sky Serpent. Super-Heavy Fighters should be immune to such effects.

**Comment by tksolway** [comment]
Will have to trace the damage function related to the EP Gun targetting the sky serpent.  There's probably a disconnect there somewhere.  If all else fails, we can prevent hte EP Gun from targetting Super Heavies, since they are always in their own flight.

**Comment by Zero1627** [comment]
$system instanceof SuperHeavyFighter
SHF is derived from ship, not system :) - need to check and if this is indeed the culprit, modify all weapons with similar capability
modification:
$ship instanceof SuperHeavyFighter

**Comment by tksolway** [comment]
The ship is the fighter flight, and the fighters are systems within that flight I believe.  Might be different for SHFs

**Comment by Zero1627** [comment]
class SuperHeavyFighter extends FighterFlight

so it's on the level of whole flight, not craft. Inside it has an actual fighter as a system just like fighter flights do.

**Comment by tksolway** [comment]
Ah, Likely the System added to the Ship will need to have a SHF attribute set to True, and that is what the gun has to check then.

**Comment by Zero1627** [comment]
I checked that already - attribute is NOT added to system, but to ship itself. What You propose would work, but would require weapon changes (in the same place) anyway - AND units' change as well. 
Please check whether current solution works - I think it should be all right and enough.

**Comment by Zero1627** [comment]
works :)))
