### ISSUE TITLE
MCV Hit Handling

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#163]
Right now Medium ships have three sections, but only one of those sections has structure.  Every System must be a member of a specific section.  I have not found an easy way of making this membership shared between sections, as it would mess with the display of medium ships quite a bit.  It would also result in a lot of complex coding to try and manage the shared membership.  In the board game Medium ships have only a single section (indicated by the strucutre).  Hit charts control what systems within that section can be hit from what angle, and what systems are "Primary" hits.  When FV was originally coded we did not use hit charts, hit system was determined by cycling through a section.  In this case, obviously MCVs needed to have three seperate sections.  However, now that we have hit charts implemented we can move the MCV implementation to match the board game.  

The change I will make is to bring the MCV down to only one section, the primary.  We will retain the three hit charts associated with each MCV though.  The hit chart will control which systems can be hit from which angles, but all three hit charts will refer to the single primary section.  So in the end it will be implemented as the normal rules.  

What you suggest is obviously a quicker fix.  If you can figure out how to pass that easily I'm all ears.

**Comment by Zero1627** [comment]
Let's get back to our discussion: what needs to be corrected?

While what You say is technically true (MCVs have one section ec), I do not believe it has any actual impact in FV besides called shots. I do remember explanation You sent me, but I do not believe it influences anything more than said called shots.

Implementation as 'section without structure' is, in my opinion, a very accurate one. It allows to differentiate which systems are on Fwd, which are Aft. And I believe that to be important fdifferentiation: that while all of them are 'PRIMARY' technically, they are still separate and cannot be hit from inappropriate hit chart.



I think good example of that is Steadfast.
She has 4 Gatling Railguns - 2 forward, 2 aft. Appropriately, they are present on both Fwd and Aft hit charts. BUT I believe 2 forward ones are hit only from Fwd table, and 2 Aft ones only from Aft chart. They should not be mixed.
Proof: look at Storm Front. She is Steadfast variant, and retains Aft Railguns, but not Forward ones. Appropriately, now RGRs can still be hit from Aft chart, but not Fwd one. To me this means they never were part of Fwd chart to begin with.

Another proof is Mogratti and Sussha: they have light weapon mounted in central position, and it has its own PRIMARY table entry. Similar weapons are on Fwd, and they have appropriate Fwd table entries.
Mograth, in that central position, has Guardian Array... and it's not hittable from Fwd table. Switching weapon in this mount to Twin Array, in my opinion (Mogratti), doea not make it legal choice for Fwd chart.

**Comment by Zero1627** [comment]
>I do not believe it influences anything more than said called shots.
At least, anything more in FV. Outside FV, I didn't see explanation for Gaim Bulkheads, but taking it literally all MCV bulkheads should be able to protect all systems, inluding PRIMARY ones. It would be very strange to me, but then Called Shots explanation was strange too, so I may be wrong.

**Comment by tksolway** [comment]
Let's be frank.  MCV SCSs are a mixed bag.  Most actually list weapon numbers on their to hit charts (or specify front and aft), take a look at the Tethys and the Maitau.  Some don't list anything, such as the Haven.  Some don't accurately represent their hit charts at all.  Look at the Xebec, all of it's weapons are in the "Primary" even though they are hit from the chart in the front.  

I think we have to use our best judgement.  I don't think we can come to a happy medium that will work for every ship.  

I'm not suggesting that we completely replace the current MCV implementation, and re-reading my last post I can see how it came across like that.  I would build this new Medium in parallel.  Quite frankly, replacing every MCV in the game is too much work.  And since the vast majority of them are working, we shouldn't have to touch them.  I do think we need a solution to the ones that don't work with the current system though.  

Take a look at some of these SCSs and you'll see what I mean:

White Star
Rolantha Freighter
Missile Barge
Bulk Freighter
Ore Barge
Passenger Liner

There are others as well, these are just the ones I have in my pile of rejects in front of me since I've been doing civs and raiders recently.  

We also have a bunch of medium ships that have been implemented with the "split", where we split primary systems among fwd and aft so they would work with the hit charts.  These could be re-implemented as designed as well.  (I can't remember any specific ones off hand, but it usually involved cargo bays).

I think it is fair to try and build these ships to target the logical systems as well.  So if there are cannons both fwd and aft, we can name them differently so they are separate systems for the hit charts to target.  I agree it doesn't really make sense for forward hits to damage aft guns.  This is already a problem we've solved with the display names though.  

As it is I think we need to do something for my growing list of ships that I can't implement under this system.  And, as I said, I'm open to your idea.  I've looked into that idea briefly in the past and didn't see a good way of doing it.  But if you can find a way to do it, I would love to implement it.  It would be easier than what I suggest.

**Comment by Zero1627** [comment]
>I agree it doesn't really make sense for forward hits to damage aft guns. 
Basically that's all my comment was about ;) . If You agree about this, I think 'virtual section' is good for everything but a name and called shots - and already works... 

I will look at called shots routines then. If they can be taught to treat all MCV sections as PRIMARY section, then everything would be fine, without need of  major cases.

Second case is systems present on multiple hit charts, but here I expect it can be solved by hit chart handling routines, as I was talking about previously.

I will look at both cases when time permits - I'd like to do so this week.

**Comment by tksolway** [comment]
I had an idea last night regarding the hit chart routines.  Make the entries that need to move sections into an array with two values, the display name and the section number.  Then when we are doing our check we can simply check to see if the result is an array, if so we know where it needs to go.

**Comment by Zero1627** [comment]
yes, that would be more generic solution - in fact, very useful at times!

**Comment by tksolway** [comment]
The targeting branch tests well.  It seems to work without issue.  

You'll need to alter the display of the hit-chart as well so that it doesn't display the hit-chart location. 

We should implement the White Star using this method as well, I'd like to test with a medium since they work a little differently than a cap, and then it will be something that will be tested in the wild as well.   

![capture](https://cloud.githubusercontent.com/assets/14058786/14623888/14aa5750-0593-11e6-8f44-a9b1a0c12cc7.PNG)

**Comment by Zero1627** [comment]
You're quick!

>You'll need to alter the display of the hit-chart as well so that it doesn't display the hit-chart location.
Frankly I'd prefer it to display it - system will be displayed in one location after all, such indication is, I think, good for player. It would be nice to replace it with section name, but I do not feel it is important/urgent.

White Star I will try to modify (add hit chart) today or tomorrow - in a separate branch, or can I continue in the same branch?

**Comment by Zero1627** [comment]
EDIT: I found responsible procedure:
https://github.com/Aatu/FieryVoid/blob/9ba7be552091d161c9bb140497ba875fdbfba04d/source/public/client/UI/shipwindow.js

function hitChartSetup

doing appropriate substitution should'nt be difficult. I will try to change numbers for actual section names (or their abbreviations, names are long), but not as top priority, ok?

**Comment by tksolway** [comment]
Do the White Star in the same branch since it requires that code to work.

**Comment by tksolway** [comment]
I wouldn’t bother listing the section it targets.  It doesn’t in game either, and it should be self-explanatory when looking at the ship layout.

**Comment by Zero1627** [comment]
OK, will do White Star hit chart in same branch, and correct display to simply skip target section - hopefully will do it tomorrow.

**Comment by Zero1627** [comment]
I think it's working correctly now :)
