### ISSUE TITLE
Markab Religious Fervor Enhancement

### ISSUE THREAD

**Issue by melkorium** [Aatu/FieryVoid#1631]
In Dilgar War supplement, Markab can fight under 'religious fervor' which lets them ram and gives +2 Ini, increase defence profiles by 10, and gives them +1 to hit roll.  Fighters also get -3 dropout roll.  Thinking about adding this as a Markab only enhancement for a bit of flavour.

All these seem to exist as part of  current enhancements, except the +1 to hit for ships (fighters can get +5 OB).  Without this I'm not sure it would be worth it.

**Comment by Zero1627** [comment]
Flat shipwide hit bonus/penalty is currently not implemented - for fighter OB modification is used instead. 

Best implementation option for ship would be to actually introduce an attribute for such a shipwide modifier, like current crit roll modifier - it won't be difficult, would require:
 - adding appropriate attribute
  - actually using it in front and back end base hit chance calculation
...and that's it for a groundwork :) . If You go for it - You may actually use it for Elite/Poor Crew enhancements as well!

**Comment by melkorium** [comment]
Cool, thanks for the idea!

**Comment by melkorium** [comment]
Added, Tested and Working :)
