### ISSUE TITLE
Markab Stun Beam Update

### ISSUE THREAD

**Issue by melkorium** [Aatu/FieryVoid#1632]
The Stun Beam in FV seems to be a simplified version, could it be enhanced using Cascor Rad Cannon as a basis, so that it uses more of it different effects listed in Dilgar War based on what system it hits e.g. disable thruster / weapons for one turn, half scanner and engine output , -4 ini for CnC,

**Comment by Zero1627** [comment]
I think that when the weapon was created, it wasn't so easy to add temporary criticals. 
Now adding appropriate functionality would be much easier than it would have been back then!

**Comment by melkorium** [comment]
Thanks, tricky ones (for me) might be getting output from scanner and engines and then halving, but I know there's getOutput functions, so can hopefully use them and then apply crits equalling half of the output.  Thruster disabling for a turn also probably needs something new, as I don't think we can disable thrusters for a turn (since they don't use power?), so thinking of a similar solution where you get output of thruster and then reduce it to 0 for a turn.

**Comment by melkorium** [comment]
Completed and successfully tested for next deployment.
