### ISSUE TITLE
section choice at range 0

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#164]
Sharlin is approached from front port side, range 0. Relative bearing: 300 degrees. Targeted is front, for some reason...

**Comment by Zero1627** [comment]
observation to self: it's not dependent on sideslips or firing unit, and it happens at range 0 only. Range 1 at the same relative bearing result is correct.

**Comment by Zero1627** [comment]
note to self: it's not only Sharlin, today I received a report about Morshin (a HCV) attacked from Aft and hit at Front...

Suspects:
https://github.com/Aatu/FieryVoid/blob/MarcinSawicki_SCS_fixes_3/source/server/model/ships/ShipClasses.php
public function doGetDefenceValue
it's possible that at range 0 validity check gives incorect results:
            foreach ($locs as $loc){
                if (mathlib::isInArc($shooterCompassHeading, Mathlib::addToDirection($loc["min"], $tf), Mathlib::addToDirection($loc["max"], $tf))){
                    $valid[] = $loc;
                }
            }

**Comment by Zero1627** [comment]
note to self: this must be something that translates to front end, because front profile is visible in targeting phase...

**Comment by Zero1627** [comment]
note to self: hit chances in log are correct (appropriate for side). But hits are still allocated at front!!!

in interface it's the other way around: front profile is used, but side is allocated as eligible for called shots...

**Comment by Zero1627** [comment]
found server-side problem: public function getHitSection
uses getDefenceValuePos to choose section - and position at range 0 is the same, getDefenceValue should be used instead.

I do not know if this will be enough to correct interface side of things (this may be separate bug).

**Comment by Zero1627** [comment]
comment to self:
https://github.com/Aatu/FieryVoid/blob/MarcinSawicki_getHitSection_bugfix/source/public/client/weaponManager.js

function calculateHitChange: is using getShipDefenceValuePos and not getShipDefenceValue...


I _think_ this is the reason of incorrect hit chance displayed, and am correcting. Thi seems independent from actual allocation of fire (server side).

**Comment by Zero1627** [comment]
it seems that getDefenceValuePos and getDefenceValue do not take roll into account... Correcting.

**Comment by AncientSion** [comment]
I just had this popping up. Hyperion in Hex, moving Jashakar into the hex after Hyperion. Upon fire, aft-section of Hyperion should be hit, instead dmg resolves versus Hyperion Front.

**Comment by Zero1627** [comment]
I have corected this bug (or at least I think so), but correction is waiting to be deployed. In the same package I corrected some other bugs too (interface showing incorect hit chance at range 0, and server ignoring the fact of target roll when allocating target section).

**Comment by Zero1627** [comment]
works :)))
