### ISSUE TITLE
Mass Driver

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#165]
Mass Driver is reported to be unable to fire at anything. SHould be able to fire at immobile units.

On a glance, it has FC vs large ships only and attribute:
 public $targetImmobile = true;

most probably effect of this attribute needs to be checked.

**Comment by tksolway** [comment]
Indeed now that we have bases this needs to be looked at.  I assume that attribute exists in the base ship class, if so we can simply set it to true in the base class.

**Comment by Zero1627** [comment]
I saw it in a base, and it IS set to true :) . But I haven't checked how it is used, there may be a typo or slight misuse that's causing problem (like with SuperHeavyFighters)

**Comment by Zero1627** [comment]
Sorry, my bad. $targetImmobile is a weapon attribute, not unit attribute. So bases do not have it set, just Mass Driver. Will need to check its usage - I see it only in /source/public/client/weaponManager.js (on a glance at least)

**Comment by Zero1627** [comment]
EDIT: Chris confirmed that Mass Driver was never functional. If it is to function, it would need to have been completed (target enormous unit, damage resolution)

**Comment by tksolway** [comment]
It would also need to be limited to only bases with Six sidings, other bases aren’t enormous

**Comment by Zero1627** [comment]
>It would also need to be limited to only bases with Six sidings, other bases aren’t enormous

It's not so direct - Narn Ja'Stat has 5 sides, Ja'Dul only 3, and both are Enormous. SInce we do not expect Enormous rules to be implemented any time soon, I think easiest way to go is unit attribute $isEnormous (or something like this ;) ). It would need to transfer to front end though, as targeting is done by javascript. Other attributes do tranfer, so it should be doable.

Also, its mode of dealing damage would need to be checked - if I remember correctly Mass Driver does overkill (it won't be stopped by Light Pulse Cannon on the surface of target ;) )

**Comment by tksolway** [comment]
Ya, it would require some work.  Also, they are considered a war crime ☺

**Comment by Zero1627** [comment]
>Also, they are considered a war crime

Not by Dilgar :P . I'm not sure they do have a concept of war crime...

**Comment by tksolway** [comment]
That’s probably why they are a dead race ☺

**Comment by Zero1627** [comment]
shouldn't be all that difficult to do now :)

**Comment by Zero1627** [comment]
Done!

Remarks:
 - weapons with no intercept degradation were introduced (paving the way for auto-intercept of ballistics)
 - even a single MD eats up all intercept capability of target
 - weapon can be actually fired at any Capital target, in any conditions. However, shot will be accurate (have any chance of actually hitting) only if firing conditions are met (both shooter and target immobile, target $Enormous==true). Player has appropriate remark in weapon, and if he fails - will be specifically informed about reason why his hit chance was 0.

Interception may be improved, but that's for a different issue (...which I intend to do soon - review I did now indicates it will be wmuch ewasier than I initially thought).
