### ISSUE TITLE
Accel/Decel while pivoted

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#166]
Bug report:
"When pivoting, my Demos had the option to accelerate or decelerate (should be illegal while pivoted/pivoting). The "apply thrust" window popped up with all thrusters greyed out, but when I clicked "OK", the deceleration happened (for free, no thrust spent!) I was able to decelerate as much as I wanted for free."

EDIT: looks like problem is connected with procedures automatically assigning thrust.

Edit: addendum:
"The option to press + or - for speed should not have been available in the first place, while pivoted.
When my Mograth (an agile ship) was pivoted, there were correctly no + or - speed arrows available."

**Comment by AncientSion** [comment]
It is not a bug with the thrust auto-allocation. movement.js has functions which check for every available type of movement, i.e. roll, accel, turn etc. Upon receing a true, the game will draw the corresponding UI icon for that action.
If you can accel a pivot'ed Demos, it means the client did draw the speed change icon, so the "can-change-speed" function returned true in the first place.

basicly:
shipmovement.js -> drawShipMovementUI
calls functions to determine what UI to draw

movement.js -> is being called
canspeedchange return true to above function -> draw UI

look in movement.js for function canChangeSpeed

**Comment by Zero1627** [comment]
thx, will look at indicated places.

**Comment by Zero1627** [comment]
Grav Drive and Pivot no longer interact correctly. need testing.

**Comment by Zero1627** [comment]
addressed!
