### ISSUE TITLE
Hyach FC Computer

### ISSUE THREAD

**Issue by melkorium** [Aatu/FieryVoid#1667]
Is able to set FC bonuses each turn.  Obvs base off AA Controller, but not sure whether to get this to toggle 3 ship variables which work like the newly added $toHitBonus e.g. $toHitBonusCap, $toHitBonusHCV, $toHitBonusMCV and it adds to them based on what player selects each turn.  Or do something fancier with notes...

Something to work on in 2024 to put Geoff out of his misery ;)

**Comment by Zero1627** [comment]
Doouglas made it!
