### ISSUE TITLE
Sensor critical: can't change EW next turn

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#171]
This critical is rolled and shown, but that's it. It does not go away, and it does not do anything.

Player may of course do as the critical asks for, but this reqires him to actually spot this critical in time, and remember what his EW allocation was.

Getting allocation from previous trn in game seems to require major changes. I propose to replace this critical with something simpler of similar magnitude (but enforced by game): 'Must use all but 1 point of EW for DEW next turn'. And, of course, make it properly disappear after one turn :) .

Tom - would You accept such solution?

**Comment by AncientSion** [comment]
The EW allocation can be easily retrieved from the database and then, just like AMMO is set for Orieni craft, can be put into the game (at the same time where ammo is set, its not too much effort).

Another workaround would be to show a popup upon initial orders when the critical is found. This would only require a minimal client side work but would still require the player to actually "play fair" and not ignore the popup.

**Comment by tksolway** [comment]
Popup is probably the best option i think. Especially if you can remind them what the ew was. Part of the issue with the crit is sometimes you don't remember what you set on the last turn

Thanks,
Thomas Solway B.Sc.

On May 4, 2016, at 3:39 PM, AncientSion <notifications@github.com<mailto:notifications@github.com>> wrote:


The EW allocation can be easily retrieved from the database and then, just like AMMO is set for Orieni craft, can be put into the game (at the same time where ammo is set, its not too much effort).

Another workaround would be to show a popup upon initial orders when the critical is found. This would only require a minimal client side work but would still require the player to actually "play fair" and not ignore the popup.

-

**Comment by AncientSion** [comment]
That again would require a bit more work because you would need to query the database to populate the popup after all...

**Comment by Zero1627** [comment]
If database is to be queried and values transferred, then this is already quite a lot of work - why not add some more and make it work as advertised. 
I wanted solution that avoids that part... but if You feel it's important, I may try to go with full functionality. Someday :P - I wanted to avoid such a deep change for, effentially, a single critical result.

**Comment by tksolway** [comment]
I understand where you’re coming from. But in the past I’ve noticed the critical but couldn’t’ remember what I’d set for EW the last turn anyway.  Which helps no one ☺

**Comment by Zero1627** [comment]
option: critical does not do anything, as of present. What if last turn's EW is included in the critical itself? (would require dynamic text of critical, but that's about it?) It would still not _do_ anything in game, but would take care of remembering without necessity to program in new windows and data exchanges...

**Comment by tksolway** [comment]
That could work.

**Comment by Zero1627** [comment]
I have reviewed the code and sadly see no option to change text as I initially wanted - as a critical is added as a class, not as a simple text entry. And approach abovew requires free text, really. See:
/source/server/model/cricialClasses.php

**Comment by Zero1627** [comment]
During other development I found out that full EW history is readily available in existing data. So it might be possible to pull this out after all. Assigning myself.

**Comment by Zero1627** [comment]
It would be difficult for little return... Just reorganizing Sensor hit chart.
