### ISSUE TITLE
Blanket DEW

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#173]
In interface (at least I hope it's only in interface) effect of blanket DEW is assigned with consideration ot units' faction, not player.
EDIT: confirmed it's interface only.

So Garut giving DEW does affect opposing Ves'Tek fighters (both Custom), but not allied Vorchan (which is Centauri).

**Comment by tksolway** [comment]
You might have to check the rules, Scout abilities might be limited to race.  Part of the reason I put the custom Minbari stuff in the Minbari folder is because Jammers are defined by race as well.  We may have to look at putting some stuff in the race folders.

**Comment by Zero1627** [comment]
>Jammers are defined by race
Yes, I found out only yesterday :) . In this case all Minbari must go to Minbari directory, official or custom... And we can't have any non-Minbari Jammers ;) (which does not seem to be a problem for now).

>Scout abilities might be limited to race
I have just reviewed ElInt functions (blanket DEW in particular) and I see no such limitation (I see only differentiation between 'friendly' and 'enemy' ships). And they certainly shouldn't protect opponents, even of the same race ;) . Perhaps somewhere exists a  race-specific ElInt function that would work only on ships of same race, but not generally available ElInt functions - unless I missed anything?
In particular, blanket DEW is defined as 'All friendly units within 20 hexes', with scout owner allowed to determine which units are friendly essentially as he wishes (useful eg. for civil war scenarios, with sudden outbreak of hostilities between units of same fleet).

Anyway, server-side everything is fine - bug is limited to interface and affects only blanket DEW. 
And it's irrelevant in a typical battle where both opponents have one faction each, and they're different factions.

*DISCLAIMER: there are some interactions with Jammer that can affect ElInt functions and are, I believe, ignored by FV (which may be considered another bug). But nothing should affect blanket DEW.

**Comment by tksolway** [comment]
Changing the naming scheme for custom ships will end up fixing this issue.

**Comment by Zero1627** [comment]
>Changing the naming scheme for custom ships will end up fixing this issue.
It definitely will not for multi-racial fleet.

**Comment by Zero1627** [comment]
note to self:
variables that should be used instead of faction: ship.userid

**Comment by Zero1627** [comment]
solved (currently deployed version with switched comparision, but that will change soon - code already changed)

**Comment by Zero1627** [comment]
works correctly :)
