### ISSUE TITLE
SHow active fire

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#174]
'Show active firing phase' feature definitely behaves strange.

**Comment by AncientSion** [comment]
problem very likely solved, see FB conversation.

**Comment by Zero1627** [comment]
noted and code modified.

**Comment by Zero1627** [comment]
I see Tom's comment that it was tested and works, so hopefully I'll close this thread soon :)

**Comment by Zero1627** [comment]
works :)))
