### ISSUE TITLE
Fire Order

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#179]
Does anyone have a defined order of functions to execute a fire order?  Or does anyone know where a  fire order is initiated in the code so I can trace it?  I'm having trouble determining where a fire order starts.

**Comment by Zero1627** [comment]
you mean when order is given (front end) or resolved (server side)?

**Comment by tksolway** [comment]
Resolved on the server side.

**Comment by Zero1627** [comment]
I am not completely sure, but I have something that looks very promising: class Firing, method fireWeapons (line 444)
file: https://github.com/Aatu/FieryVoid/blob/master/source/server/handlers/firing.php

**Comment by Zero1627** [comment]
...which is called from class Manager method startEndPhase (line 687) in file:
https://github.com/Aatu/FieryVoid/blob/2c7728995a49687039683797c6816b642f5705dd/source/server/controller/Manager.php

**Comment by tksolway** [comment]
Yarr, that looks like the start point.  I'm going to have to find time to trace it to figure out my scatterguns.

**Comment by Zero1627** [comment]
note that this is centrally the area where I do heavy changes right about now, so this thread should perhaps be closed ;)

**Comment by Zero1627** [comment]
Closing this thread as no longer relevant.
