### ISSUE TITLE
Rename all Unofficial ships to fit standard

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#181]
We will need to create a branch and do a cleanup of all the unofficial ships already in the game.  

New standard is (u) Ship Name (Year)

We won't be adding any other information such as source of the ship etc.  Just labeling it as unofficial.

**Comment by AncientSion** [comment]
I think a futureproof version would only add the YEAR as the ship class method and than append the name span to also display the YEAR attribute in the shipwindow / buy GUI as opposed to altering the ships name.
Also, the same is true for the (u) prefix. I dont think its a "smart" solution. It would require minimal extra work instead add two attributes.
Doing this will allow for some really nifty stuff, for example adding a YEAR filter which will allow you to filter ship classes by ISD, something that is very interesting when it comes to skirmishes between ANYTHING in regards to the Dilgar War, i.e. anything that involves Dilgar, EA, Drazi. And possibly more later.

i.e. 

class OrestesGamma extends BaseShip{
    
    function __construct($id, $userid, $name,  $slot){
        parent::__construct($id, $userid, $name,  $slot);
        
		$this->phpclass = "OrestesGamma";
		$this->unofficial = true;
		$this->isd = 2219;



The client would construct the shipwindow like 

span.innerHTML = ""

if (ship.unofficial) {
span.inenrHTML += "(u)";
}

span.innerHTML += ship.phpclass;
span.innerHTML += " - ISD: ":
span.innerHTML += ship.isd;

In that specific case, the ship base class would be set to $this->unofficial as false by default.

I know you explicitly mention only to rename UNOFFICIAL ships. However, editing them like is suggested above will at the very least make them future-proof, and add proper functionality for further feature (i.e. at some point, also edit stock ships and a proper filter will still work with unofficial ships).

So, for Wolfgangs campaign ships, please consider doing it properly. Only editing the name string sounds like a rather short-sighted decision to me.

**Comment by tksolway** [comment]
That is a good idea Chris.  If we leave the ISD as “” in ships where we don’t want the year displayed it would work just fine as well.  Perhaps that is what we set the default as in the baseship.

Is there an easy way to justify the year so it is displayed at the far right of the window?  That way it wouldn’t be at the end of all the names.

**Comment by AncientSion** [comment]
Having the "year" string appear at the very right of the current "name" span will only work if it becomes its own span. I.e. after appending the "shipclass name" span element to the parent (div) element, one would have to create another span, set the spans innerHTML to the ships ISD,set a certain top/right/position css property (bah layout) and append this span to the parent div. The Div would now hold one more span. Layouting with CSS is a bitch, but without creating a new span element this layout issue cant be done.

Its easy to do, just needs a bit of time to figure out the exact css properties and pixel values for that specific layout. I can do it - or you can try.

**Comment by tksolway** [comment]
I might give that a try. It would help me figure that code out again. Its been a lot of years since ive done css

Thanks,
Thomas Solway B.Sc.

On May 13, 2016, at 3:59 PM, AncientSion <notifications@github.com<mailto:notifications@github.com>> wrote:


Having the "year" string appear at the very right of the current "name" span will only work if it becomes its own span. I.e. after appending the "shipclass name" span element to the parent (div) element, one would have to create another span, set the spans innerHTML to the ships ISD,set a certain top/right/position css property (bah layout) and append this span to the parent div. The Div would now hold one more span. Layouting with CSS is a bitch, but without creating a new span element this layout issue cant be done.

Its easy to do, just needs a bit of time to figure out the exact css properties and pixel values for that specific layout. I can do it - or you can try.

-

**Comment by tksolway** [comment]
I've added the below to the ship details window.  I'm having trouble finding where to add the pertinent details to the names displayed in the list of ships when building a fleet.  I think it might be this line, but haven't managed to parse it out completely yet.  

`			for (var index = 0; index < jsonShips[faction].length; index++){
				var ship = shipList[index];
                var targetNode = document.getElementById(ship.faction);

                var h = $('<div oncontextmenu="gamedata.onShipContextMenu(this);return false;" class="ship" data-id="'+ship.id+'" data-faction="'+ faction +'" data-shipclass="'+ship.phpclass+'"><span class="shiptype">'+ship.shipClass+'</span><span class="pointcost">'+ship.pointCost+'p</span><span class="addship clickable">Add to fleet</span></div>');
                    h.appendTo(targetNode);
            }
`

![capture](https://cloud.githubusercontent.com/assets/14058786/15269453/f5e6e760-19bb-11e6-985c-6d6bc2693908.PNG)

**Comment by tksolway** [comment]
figured out how to add the (u) to the list, but it must be after the sort. since it doesn't get pushed to the end (or beginning).  Will have to try and find out where it sorts the list.

**Comment by tksolway** [comment]
Yay, found the sort function and added a second sort to move all the unofficial ships to the bottom of the list.  

Should be good to go for just the unofficial naming.  I can pretty easily add the ISD to the end of the name now as well, I think I'm going post for feedback on that idea though.  As I'm not sure what people think of it.

**Comment by Zero1627** [comment]
please tell me later what I shall go for in new ships.

**Comment by Zero1627** [comment]
so     
$this->isd = 2219;

...and delete from name itself, leave adding it to scripts? Seems nice :)

**Comment by Zero1627** [comment]
question: when do You plan to deploy these scripts? I use new variables for some time now ;)

**Comment by tksolway** [comment]
Did I not merge this change into the main game?  I assume it is ready to go, otherwise I wouldn't have asked everyone's opinion.  I can try and check it out this weekend.

**Comment by Zero1627** [comment]
Most definitely this didn't go live yet ;)

**Comment by tksolway** [comment]
K, I'll try and look at it this weekend.  Heh Winter is coming maybe I'll have some time now to look at some stuff again.  Summer is so horrible for finding time to sit down on the weekend and do anything.

**Comment by Zero1627** [comment]
>Winter is coming 
You sound very Stark ;)

**Comment by tksolway** [comment]
I'm Canadian, where do you think he got the idea for the Starks :-)

**Comment by Zero1627** [comment]
sorry for stealing this from You - I'll do it as part of a larger change. I have an idea how to do a pretty complex display without really changing anything in core ;)

**Comment by Zero1627** [comment]
rename is, I believe, done - CUSTOM status is clearly visible on selection screen. Ships need to be overhauled to take advantage of new display options, but that may be done gradually (as it is with ISD).
