### ISSUE TITLE
ISD Date

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#184]
Create a branch to support adding the ISD date to the ship info screen.  add value to base ship class with a default of "Unknown" and then override in each ship as we go along.  

Would take a while to do all the ships, but it is something we could slowly propagate.

**Comment by AncientSion** [comment]
So i left some remarks in the other (u) thread on this topic, sorry.

**Comment by Zero1627** [comment]
frankly I don't care for it all that much :) - thoiugh I see a serious discussion happens in FB. Whichever way people wan, I guess, as long as someone will fill that data :P . I may do it in changed and/or new ships as required, as I do with hit tables.

**Comment by Zero1627** [comment]
I'll do it as another thread, closing this one as redundant.
