### ISSUE TITLE
Jammer at start of turn

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#186]
Wolfgang's comment:
I just made a test game to look into one problem regarding jammers. Since power allocation is done at the same time as EW, you can't target a ship that turns off its jammer with your Scout and give SOEW to antoher unit. same is true for ballistic launch ranges. Even if the ship in question turns off the jammer for multiple turns in a row, I can never do that. That is really hurting in some scenarios (or when fighting a White Star with a billistic ship, which often turns off the jammer.

proposed solution:
I see what the problem is. But I don't see a way around it with Power and EW crammed into a single phase.
Well... perhaps if interface saw enemy's previous turn Power allocation... This way if jammer is off, it would be disabled at the beginning of next turn (even if it's turned back on). Not perfect, but better than nothing, and perhaps doable  .

**Comment by tksolway** [comment]
I’m not sure we can really change this, it might just have to stay one of those annoying proclivities of FV

**Comment by Zero1627** [comment]
For a player, Power allocation remains the same next turn - so this information does exist. The only necessary change shall be to use this information for opponent too (and just for the jammer would be enough). This may not necessarily be easy :) , but I think it should be _possible_ without major changes - and indeed would improve balistics vs Jammer situation

**Comment by Zero1627** [comment]
...I even found a function repeatLastTurnPower :)

**Comment by Zero1627** [comment]
well, that's not it - this fragment is called AFTER determining what's shown. Next attempt prepared, deeper this time.
source/public/client/power.js about line 59

**Comment by Zero1627** [comment]
done!!!

It turned out that on load, Power orders for opponent are cut out in Initial phase. I made an exception for Jammer, as well as appropriate check in code.
