### ISSUE TITLE
Randomness

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#188]
As I was parsing the code I noticed that everything is determined with mt_rand()

I've changed it all to random_int because:

http://php.net/manual/en/function.random-int.php

mt_rand is recognized as a biased randomizer, it is not useful for something like this.  I only know this because randomziers were something I worked on specifically in University.

**Comment by tksolway** [comment]
Annoyingly the server is not running a late enough version of PHP to handle this.  I'm going to have to track down a different version of the code.

**Comment by AncientSion** [comment]
The server is RUNNING very old php. In fact, so old you cant init an array with [] :dancer: I 
I believe its 5.3.

**Comment by tksolway** [comment]
Indeed, I was able to find random_compat though.  The community rebuilt random_int for older versions of PHP.  I'm testing that now.

**Comment by Zero1627** [comment]
:)

**Comment by tksolway** [comment]
This was deployed a while ago
