### ISSUE TITLE
ZOMBIES

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#202]
"One Heavy Plasma Cannon destroyed the reactor, the other the structure. Ship is not destroyd in game."
http://fieryvoid.net/hex.php?gameid=3415

...which is strange, as destruction should be immediate in either case... but perhaps it was one shot that did both things and code sort of cancelled each other?...

**Comment by Zero1627** [comment]
from submission:

When you look at the firing in FV, the damage would not have been suffiecient to destroy both in one shot and two Plasma Cannons did hit, but for both only the damagte was written, nothing was "destroyed" (structure was at only 13 points prior to the weapons fire, the reactor was the hit for 22 damage).
I like the Vorlon option. :)
Oh and the ship is rolled and pivoting, if that is important. :)

me:
hmm... target is Centurion, so I think it MIGHT be the case of Reactor overkill destroying PRIMARY structure...

**Comment by tksolway** [comment]
That is an interesting bug, certainly a corner case.

**Comment by Zero1627** [comment]
so it is. I even looked a bit into code, but haven't found anything yet. I suspected that simultaneous destruction of 2 critical things might have caused trouble, but on a glance it seems it should be irrelevant...

**Comment by Zero1627** [comment]
EDIT: I have reviewed fire phase. One Heavy Plasma caused 13 damage (the Struct-killing blow, most probably), the other 22 (which matches Reactor structure exactly).

Reactor got a critical (as if it was just damaged), ship is not destroyed EoT.

Ship is rolled, which _should_ be irrelevant ;) .

**Comment by Zero1627** [comment]
working hypothesis #whatever: plasma damage was enough to destroy system, but with very little overkill... $damage-$armor was a negative number, kill was done only due to Plasma properties - code _seems_ to not take this into account. But Plasma is taken into account all righ usually, so need to check more!

**Comment by Zero1627** [comment]
http://fieryvoid.net/hex.php?gameid=3450
Tinashi 1 has a retro thruster at 0/8 structure, but not destroyed...

**Comment by Zero1627** [comment]
currently I have no more ideas why such things happen - and they can't be replicated on demand :(

**Comment by Zero1627** [comment]
I found a possible reason: Plasma weapons have range penalty to damage, and it may have a fractional part (it's not rounded) - so does 5.9 points of damage - this may leave system at 0.1 damage or something like that.

**Comment by Zero1627** [comment]
I _think I corrected the issue. I'm closing the thread (but not deploying immediately).
