### ISSUE TITLE
change password

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#216]
such feature was required a few times already, and would be occassionally very useful - and shouldn't be too difficult to program in.

**Comment by tksolway** [comment]
If anyone is looking at the authentication piece we also need to sanitize the input to prevent SQL injection.  Something like this probably has a library out there that could be used for it, I just haven’t had time to look.

**Comment by Zero1627** [comment]
would be nice, but that's not high on my priority list - I plan to do something quick and dirty (...just like current registration page). I understand Your point and it's valid, but it needs a separate modification.

While we're at it, sending passwords in encrypted form would have been nice too ;) .

**Comment by tksolway** [comment]
The encryption would be nice, but you’d have to use a module for that, unless you just want to do a one way hash.

The sanitizing is easy, all you need to do is remove a few characters from the input in the user name and password

**Comment by Zero1627** [comment]
like this?

$username = htmlspecialchars($username);
$username = $this->DBEscape($username);

**Comment by tksolway** [comment]
Pretty much, but there’s likely a filter for SQL specifically.  The worst offender is ‘ and SELECT

**Comment by Zero1627** [comment]
simple but seems to work :)
