### ISSUE TITLE
MLPAs

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#217]
Medium Laser-Pulse Arrays are buggy as hell!! Especially when it comes to powering down (not always possible) and bringing up (they usually don't get up) and forced shutdown (..with various effects ;) )

**Comment by tksolway** [comment]
Yep, have been forever as far as I understand, I’ve never looked into them.

Personally, I find the ships they are on are over costed anyway.  But I know some people really love them.

**Comment by Zero1627** [comment]
personal preferences, as usual :) . But weapon themselves are buggy, which isn't nice. I'll try to do something about that (hopefully).

**Comment by Zero1627** [comment]
HLPAs are working well - once I have appropriate graphics I'll do MLPAs in the same way and install them on EA ships.

**Comment by Zero1627** [comment]
done and working :))))
