### ISSUE TITLE
Pulsar rules

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#228]
Hi all,
I'd like to modify Brakiri light weapons (Graviton Pulsars and Gravitic Bolts) behavior.
Current: firing at boosted power increases turn delay (which is strictly as the rules define it, but doesn't make much sense).
Proposed: firing at boosted power forces a cooldown period (which is as I remember it was explained on old B5Wars.net forum).

Sadly I haven't managed to get a ruling from Bruce (he said he doesn't remember details). 

My interpretation would boost Brakiri, when You compare it to current state of things, which I think would be all right :) . Effects when compared to current:
 - You may shut down a weapon after firing and it won't need a lengthy power-up when enabled back
 - while some weapons are cooling down, their power is available for use elsewhere

Question - can I go ahead with it (...someday...), or do You disagree with me? (I do not intend a vast discussion here - if You disagree on any basis, simply say so and I won't touch this area).

**Comment by tksolway** [comment]
Rules (kitchen sink pg 124) are pretty clear that it decreases the fire rate.  I’m also not sure if Cooldown is properly implemented in the game, since I don’t see cooldowns associated with weapons used in sustained mode.

I think changing this would be pretty massive.  There are a lot of brakiri ships with a significant number of these weapons, I’m looking at you Halik, and this would give them that ability to concentrate a lot of firepower into a small arc one turn, and then put out the same level of firepower in another arc the next turn.  Part of the Brakiri disadvantage is their arcs.  This change would essentially do away with that disadvantage for many of their ships.

**Comment by Zero1627** [comment]
>Rules (kitchen sink pg 124) are pretty clear that it decreases the fire rate.
Sure they do, that's what I said: 'which is strictly as the rules define it' . 

I stand by that it doesn't make much sense though. Say, I shut the weapon down after firing (rules do not prevent me), wait a few turns, then power back up... and I have increased recharge time. 

If You disagree, I simply won't do it and leave things as is.


> I’m also not sure if Cooldown is properly implemented in the game
It's not at all. But 'forced shutdown' critical works all right, and that's what I technically mean. 'Cooldown' is just fluff reason.

>I think changing this would be pretty massive.
Not at all. Delete (comment out) current code increasing recharge rate, put appropriate critical in. Plasma Torch should be an almost-perfect model (only difference is that in Torch case critical is an option indicated by roll, here it would be mandatory effect).

>There are a lot of brakiri ships with a significant number of these weapons
Just 2 weapons (Grav Pulsar, Grav Bolt). Used in a lot of places, but that's irrelevant - weapons would be modified, not ships.

>this would give them that ability to concentrate a lot of firepower into a small arc one turn, and then put out the same level of firepower in another arc the next turn
I think exactly that was the intent. This would mean power management on Brakiri ships do get really important. Also, You can concentrate firepower in this way - but only at the cost of deliberately making a hole in own light weapons coverage - both on current turn (to get power) and next one(s) (cooldown on powered up weapons).

**Comment by tksolway** [comment]
I don’t like the idea of making any sort of custom changes that aren’t required.  There are some places where this was done due to engine limitations.  But this is different.

**Comment by Zero1627** [comment]
>I don’t like the idea of making any sort of custom changes that aren’t required.  There are some places where this was done due to engine limitations.  But this is different.

I just don't consider it custom :) . But ok, no problem - I'm dropping the issue.
