### ISSUE TITLE
can't issue Initial Orders bug

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#234]
Chris, I flag this for You because I'd like to hear Your thoughts on the mattter, if any :)

Problem: can't issue initial orders. Sometimes it's 'cannot achieve player lock' result, at other times it's just no effect.
So far problem happened in a few very large battles (one about 60 units, the other over 70, combined). 

I have tracked the actual shown error - it's nothing for the first time (player lock is achieved, but never released, suggesting some kind of dump in between), 'failed to achieve player lock' for further attempts within 15 minutes (previous lock still holds).

I haven't, however, managed to find the actual error (I expect some kind of dump between player lock and its release...). Do You have any ideas, on the problem itself or ways to track it down?

Given that it only happens in large battles, perhaps there's some issue with transferring data from js layer to php? Perhaps some limit on variable size?...

Problem is not happening immediately, in my battle (3496) it happened in turn 5 :)

**Comment by AncientSion** [comment]
So i assume we know have the very large fighter battle as well as the campaign battle between you and Wolfgang as games where the Problem occured ?

**Comment by Zero1627** [comment]
Yes. Fighter battle had (I think) over 50 units, campaign battle over 70. 
I have issued EW orders in campaign battle by direct injection into table and we're in movement phase. We'll see what'll happen in next Init...

**Comment by Zero1627** [comment]
BUT I have played a few 50+ battles with Wolfgang already...

**Comment by AncientSion** [comment]
Okay.
Firstly, i have no idea why exactly is causing the error.
However, considering we know the error string, we can search the game to see where it actually breaks.

which would be Manager.php - 318 which then leads to
    
    public function getPlayerSubmitLock($gameid, $playerid)
    {
        $result = false;
        try {
			if ($stmt = $this->connection->prepare(
                "UPDATE 
                    tac_playeringame
                SET
                    submitLock = now()
                WHERE 
                    gameid = ?
                AND
                    playerid = ?
                AND
                (  
                    DATE_ADD(submitLock, INTERVAL 15 MINUTE) < NOW()
                OR
                    submitLock = '0000-00-00 00:00:00'
                )"
            ))
            {
				
				$stmt->bind_param('ii', $gameid, $playerid);
				$stmt->execute();
				
                if ($stmt->affected_rows > 0)
                    $result = true;
				
				/* close statement */
				$stmt->close();
			}
        }
        catch(Exception $e) {
            throw $e;
        }
        
        return $result;
    }

**Comment by AncientSion** [comment]
So, i guess the query, for some reason, the query returns false.
Aatu for the most part uses PHP prepared Statements for DB queries which are very hard to debug.
You could add a Debug::log in the TRY clause and the CATCH clause to see where exactly it Fails.
Also, uncomment the various debug::log lines to see what Parameters were passed.

It would make sense to only make These changes when the next Initial orders Phase is up AND throwing the error, otherwise the logfile will be spammed with too many entries to see the one we are acrtually after.
THats the best i can do right now.

**Comment by Zero1627** [comment]
Sorry Chris, I guess You missed this in my text. I have found the reason why there is the message (I'll explain below). But it's not the direct cause of problem.

Event chain, as far as I have managed to check so far:

First attempt:
 - player tries to send orders
 - player lock is set
 - further procedure gets somehow derailed...
 - player sees the same s creen, nothing happens (unless he reloads, he'll be beack before issuing orders)

Second attempt (if quick enough):
 - player tries to send orders
 - lock is not possible (because it was set in previous attempt...)
 - player receives  'cannot achieve player lock' message (which is CORRECT under the circumstances, not a bug at all)

What I need, is find where it derails, and why ;) . It seems it's somewhere in a series of database updates bound into transaction, but that's it.

**Comment by Zero1627** [comment]
in general, I have an impression that very large battles do have unexplained problems... This may mean there's trouble with memory and/or data transfer from web page. Which can't be easily solved (would need to rewrite core code - write a new game essentially), unless a particular troublesome point is found (not likely).

I will drop it for now (although will not close the issue, maybe someone will have a brilliant idea in the future :) )

**Comment by Zero1627** [comment]
I have cleared most game-related tables (cut down data from turns far enough in the past) - and game started to accept orders again.


I think this confirms the theory that something memory-related (whether data size in itself, or variable limit, or html/ajax transfer limit, or something...) is the culprit.

Currently I assume this is irrepairable, but at least now I know the solution ;)

**Comment by tksolway** [comment]
Does the game cleanup data in the DB from games that have been completed?

**Comment by Zero1627** [comment]
I have no idea, would have to check in the database. But I don't think so - in some tables I saw entries with  3-digit game IDs...
But, for a given game, only data related to that particular game would be loaded.

**Comment by Zero1627** [comment]
Tom, I have just accidentally tested that game DOES delete data of old games. So now we know :) .

**Comment by tksolway** [comment]
Cool ☺

**Comment by Zero1627** [comment]
I tried to minimize number of moves loaded to 2 turns in the past. Perhaps it'll help. It may cause incorrect section choice for range 0 firing against objects that are not immobile (eg. moved, but more than 2 turns ago).
