### ISSUE TITLE
Movement log does not work over multiple turns

### ISSUE THREAD

**Issue by Aatu** [Aatu/FieryVoid#25]
Revise the check that makes sure that certain movement is not already on list. Currently prevents new moves from next turn. Also take a look into log entries that claim start and end cordinates are same.

**Comment by Zero1627** [comment]
movement from previous turns is not all that relevant, really. But it would be nice do display all moves (even if just as a check that a particular unit moved), even if it stands in place.

**Comment by Zero1627** [comment]
I do not think this is an issue.
