### ISSUE TITLE
Reset orders for ship

### ISSUE THREAD

**Issue by Aatu** [Aatu/FieryVoid#35]
Add buttons to bot panel to reset EW and Power. Make ctrl + click on cancel move to cancel all moves for the ship

**Comment by Zero1627** [comment]
Aatu, this is actually a marvellous idea. And with new interface they could be added together with other icons (select ship, add EW...). They need to appear only in Initial phase of course.

Call this a reopening :)

**Comment by Zero1627** [comment]
Thought: only in Initial phase, on Sensors (EW) and Reactor (Power). Much needed!!!

**Comment by Zero1627** [comment]
Thought: with boosted system highlighted AND disabled boosted systems no longer drawing power, resetting Power becomes not so important. 

Resetting EW is much needed!

**Comment by Zero1627** [comment]
Reset EW is ready.

As remaining points aren't that important, I am closing the issue.
