### ISSUE TITLE
mass mode change

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#440]
Once upon a time TKS did a great enhancement allowing to select or power up/down all weapons of a given type (hence I include TKS here).

Could similar thing be done for weapon mode change? It would help things like Nova trying to alpha strike with guns in Pulse mode :)

**Comment by tksolway** [comment]
Wasn’t me ☺  Wish it was ☺ I expect that it is all linked to the input from the user, you could link it to another hot key.

**Comment by Zero1627** [comment]
was it Chris then?... r-click on Power button / r-click on weapon... I'd like similar r-click option on mode change button, too :)

**Comment by AncientSion** [comment]
It was me. I dont TKS did anything JS at all.

The eventlistener that handles right-click is called contextmenu regardless of jquery or plain javascript. So you can search for ".contextmenu(" (jquery) or "'contextmenu'" (plain) to find the appropriate binds.

**Comment by Zero1627** [comment]
thx Chris!

**Comment by Zero1627** [comment]
I am attempting to do it!

**Comment by Zero1627** [comment]
done!!!!!!!
