### ISSUE TITLE
Abbai weapons

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#470]
I was thinking of taking on the Usuuth in the near future.  They just need some basic weapons built.  Nothing ground breaking, just new numbers.  Can you post the places where I need to declare a new weapon here for posterity?  I know it needs to be added to the autoload, and I remember there is somwhere in the JS as well.  

Barring that, I can generate a list of weapons for you to build again as well.

**Comment by Zero1627** [comment]
To get a new weapon, You need:
 - weapon class (obviously), in /server/model/weapons
 - weapon class placeholder for javascript - in /public/client/model/weapon (mor eor less reflects the above)
 - index in autoload.php (this one You know)

**Comment by tksolway** [comment]
I’ll give this a try and see how it goes.

**Comment by tksolway** [comment]
Looking into the Abbai, the only thing we really need is the Particle Impeder.  It's essentially a weapon that is only used for intercept.  We could implement it as something that does zero damage with -3 intercept.  Unless you have a better idea of how to build a weapon that doesn't fire normally.

**Comment by tksolway** [comment]
hmmm, that being said, it looks like the SentinelPointDefense might already be setup that way, Remind me, that is capable of defending other ships as well right?

**Comment by Zero1627** [comment]
Yes, Sentinel and Guardian Arrays are capable of protecting other ships under certain  circumstances. I see no mention of such capability in Impeder's description though?

Particle Impeder should be able to protect from uninterceptable weapons, which is non-trivial but should be doable - if You want to stop at this point.

The problem I do see is that Impeder has an ability to accept EW points to enhance its capability - those points function as 'Directional DEW' (enhanced so it affects fighters as well!) as well as enhance Impeder's intercept rating. This is difficult enough that I have no idea how to implement it. I think You'd have to skip this ability... Maybe give it EWeb instead? (very different effect, but of comparable magnitude and purpose...)

**Comment by tksolway** [comment]
EWeb is a good idea.  I agree that implementing the last part would be a significant endevour.  I think I would be happy just to get it out as an approximation of that Impeder’s ability.

**Comment by Zero1627** [comment]
I have talked with Wolfgang. He is opposed to straight EWeb idea, but we have devised a different approach that I like and should be doable without that much fuss.

Impeder would have:
 - intercept uninterceptable weapons (hopefully I;ll be able to implement this one, its probably the toughest)
 - acts as EWeb but vs fighters only (this is easy to do in shield system methods)
 - can be pumped with extra power to increase intercept rating
 - Abbai ships get Sensors reduced by 1 from what they should have, and given appropriate Extra Power to play with.

What's Your opinion?

**Comment by tksolway** [comment]
Comments Below:


·         Intercepting the Uninterceptable would be great

·         I think that having them act as a E-Web against fighters only would be a good compromise.  I believe it would be pretty difficult to implement the EW addition to them.

·         Sounds good, but what kind of power boost would we be looking at there?

·         That sounds doable, I think any Abbai player would be spending at least one of their Ew on their impeders per turn anyway.

**Comment by Zero1627** [comment]
I will do such weapon then (...AFTER I finish current open project though, especially as I do a major change to mechanics of interception there...).

>Sounds good, but what kind of power boost would we be looking at there?
I think 2 power per point (maybe 3), with a really high cap (like +6 maybe?...). Exact values may be easily tailored afterwards if playtests indicate so (once all difficult mechanics are in place).

That should be somewhat less powerful but more flexible than original - overall I'd say close enough.

**Comment by tksolway** [comment]
Sounds good,

For the power option though, maybe have it ramp up like most other power out there.  Pay the current intercept value (standard looks like 3, so 3 power to go to -4, 4 power to go to -5 etc.)

**Comment by Zero1627** [comment]
Can do (standard is like Sensor  - new value, not old - but I can make a new schema) . I think it's to much though.

**Comment by tksolway** [comment]
I guess the real question is, just how much extra power can you get on an Abbai ship, but I’m not really attached to my idea either.  So I’l leave it to you since you are going to do the coding ☺.

**Comment by Zero1627** [comment]
ability to intercept uninterceptable weapons is already done, as a simple $canInterceptUninterceptable flag :) . Of course as part of still-not-ready package ;) (but at least it's no longer causing outright dumps on phase transition...)

**Comment by Zero1627** [comment]
I proudly announce that Particle Impeder is up and working... but lacking graphics 🙂 .

As an example, it can be seen installed on Target Drone: https://github.com/Aatu/FieryVoid/blob/master/source/server/model/ships/customs/technicalTargetDrone.php

I don't have appropriate icon - using Interceptor for now. Also, I didn't manage to persuade FV to display current output, shield-style, so it's a bit difficult for opponent to find out whether Impeder is boosted just on a glance.

Atherwise all advertised features should be there and working!

**Comment by tksolway** [comment]
Wow, that’s mastery at work Marcin.  I’ll admit I haven’t looked at anything this month, family is around for Christmas.  Hopefully I’ll have time to do a weapon graphic and build out the ships in January.

**Comment by Zero1627** [comment]
just be aware that all the changes aren't yet deployed live (doing final tests of my new firing solution...). 

They are pulled into Master though, so new branch You create should have them all right.

**Comment by Zero1627** [comment]
Quad Array ready. Special weapons halfway done.

**Comment by Zero1627** [comment]
Abbai weapons are ready and tested. Tom' I'll create new thread for You for Abbai ships themselves (I'll include details on new weapon creator calls).
