### ISSUE TITLE
LCVs

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#471]
Hey, I looked at the Drakh LCV, the hit chart doesn't have to be that complicated, you could use the same idea that the OSATs use.

**Comment by Zero1627** [comment]
true, but I made it MCV technically, so I use MCV hit chart as well. There's no difference as to actual behavior, and it was easier for me to just do it ;)

**Comment by Zero1627** [comment]
as there's nothing to be done here, I'm closing this issue.
