### ISSUE TITLE
Advanced Armor and effects

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#473]
Advanced Armor should be immune to effects from weapons (like armor ignoring or reducing.

This, however, needs to be done from weapons' end: effect should check for AA and disable itself if appropriate.

**Comment by tksolway** [comment]
Is the advanced armour tag on the ship class?

**Comment by Zero1627** [comment]
Yes, it's so defined - but system cconstructuors do check for it and pull the value (so incoming shot checks target system only, not ship itself - and also 'advanced armor' mark is visible on systems).

This works for fighters too, although it's not visible for player.

**Comment by Zero1627** [comment]
Tom, for Your benefit: Advanced Armor already works fine (esp. in regards to weapon class), except it's not affecting special properties of incoming weapons (which it should negate)(hence this thread).

**Comment by Zero1627** [comment]
Updated weapons to NOT cause effects if target has AdvancedArmor.
Almost exclusively Special and Molecular weapons, as it turned out.
