### ISSUE TITLE
(Client): Event log

### ISSUE THREAD

**Issue by Aatu** [Aatu/FieryVoid#5]
Design and implement a better combat log, and logging for movement, critical hits and all other actions relevant to the game.

Ideas:
- Display the firing or movement animation while clicking the event
- Allow expanding a single event to display additional information
  - Display detailed damage and critical hit report for a single firing event (Needs a link to critical pointing to causing fireorder)
- Add clear headers for turns and phases
- Color code enemy and friendly ship names
- Automatically minimize old turns (but allow them to be reopened at will) 
- Allow minimizing of the whole log window

**Comment by Zero1627** [comment]
Current log is good enough, I do not see any major overhaul due to this thread coming.
