### ISSUE TITLE
Adaptive armor

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#612]
With new interface adaptive armor is out - there are no buttons that allow its management. It would be nice to bring them back... in some form.

**Comment by Zero1627** [comment]
Proposal: dedicated armor management system (unhittable), for which appropriate icons would be diisplayed

**Comment by tksolway** [comment]
I like this idea.  with the hit chart, we can create unhittable systems now, so that shouldn't be an issue.

**Comment by Zero1627** [comment]
I like it as well, especially as underneath logic would be usable for a few other advanced systems. If I manage to do it as planned - Pak'Ma'Ra' and Vorlons will move from "science fiction" to "difficult" category...

But it's a difficult mechanics to do, will tackle it only when I have some free time for FV development that I expect to last for a week or two ;)

**Comment by Zero1627** [comment]
Essentially done, extensive tests remain!

**Comment by Zero1627** [comment]
tied closely to #674 , I'm closing this thread and leaving #674 open.
