### ISSUE TITLE
Adaptive armour (as a ship wide feature)

### ISSUE THREAD

**Issue by Aatu** [Aatu/FieryVoid#65]
Adaptive armour for white star.  Implement as a system that is displayed next to the SCS. (under the ship picture, for example, not as a normal system). Allow same kind of UI to toggle what damage type is choosen.

Also, make sure that all weapons have consistent damage type as a variable.

**Comment by tksolway** [comment]
First Step would be to add a variable to the weapon class called DmgType
Each weapon already has a damage type that is added during sub-system construction for the data window, we can simply define this variable at the same stage.  Since I'm new to the code I'll wait for agreement from Chris or Jasper on this issue before I begin adding this variable.

**Comment by AncientSion** [comment]
i dont think that is necesarry.
Each "gun" is a class extension in the first place, which again is an extension of the general weapon class.

i.e. 
MediumPulse extends Pulse extends Weapon

So if you want to know if a weapon is of Pulse type, you dont need a variable for it.
You can simply do PHP
if ($weapon instanceof Pulse) which will return true or false.

For Javascript you can check heritance, too but i believe ist necesarry for this Feature.

What needs to be done:
Client: in Initial orders, similar to "defensive fire" in Fire Phase, show a button in the ship SCS below the ship Icon. (this is done in shipwindow.js)
Clicking this Icon will open a window where you get a pull-down menu with ("Laser, Pulse") blabla.
Player selects one entry and hits ok.

On SUBMIT of Initial orders, ajaxinterface.js triggers and sends the EW to the server. At that point, it can also send the "String" choice from the pulldown menu to PHP, too.
Now you go to PHP (should be Manager.php, very bottom is the Ajax/Json Interface), put the string choice to server database using DBManager.php.
It's not trivial :(

After that is done, we would evaluate how to apply this upon fireorder Resolution.



quick note:
Manager.php is the file that outlines the flow of the game, it manages the different phases and gameflow and the Transition between phases.
DBManager is the file that exclusivly works with my SQL, putting and pulling data from the DB.

**Comment by jvanrosmalen** [comment]
As Christian has already mentioned, it would be easier just to check the class type of the weapon that hits you.

What I am more interested in, is how to implement the Adaptive Armor itself. I suggest treating it as a system with 0 health. Because the system would have 0 health, it would not be included in the calculations to see what systems are hit.
You should override the method isDestroyed (defined in the super class ShipSystem) to always return false I guess, as the adaptive armor system cannot be destroyed.

I think the system should then be added to the primary section. The icon for the system could then show the standard rating plus the released (but not yet assigned) armor points in the same font/way as loading time and turns loading with weapons. (So 3/1 means: this is an adaptive armor with rating 3 and it has 1 released point. When the player assigns this point, the display would be 3/0 again.) When right clicking on the system you would get a pop-up with released and assigned points.

Would the above be a solution worth considering?

**Comment by AncientSion** [comment]
why does it need to be a system in the first place ?
Why not put something like $public adaptiveArmour into the class WhiteStar. It would be better for performance, because if you are checking IF a ship has adaptiveArmour (for dmg resolution) you just look for that variable at the very top of the tree instead of having to loop over all the systems and and "hit" an instanceof adaptiveArmour at some point.

Also, by putting it to the ship class directly itself it would also be faster to build up the GUI in initial orders. No loops is the key.

**Comment by tksolway** [comment]
I'll make a pull request so you can check out the branch I'm working on, it isn't ready for merge yet.  It centres around an array of adaptive armour values.  I think we do have to go by Class rather than type of weapon as adaptive armour is set to Particle or Molecular, while you can have particle, molecular and gravitic pulse weapons.  I also wouldn't think it needs to be a system, if you look at my pull request, I've placed everything at the ship level.

**Comment by tksolway** [comment]
The array I've added could work as the base for the list presented in the ship window.  Also it will contain the actual values the users sets.  Note, I would need help with this, I've never programmed an interface like this.  

There is a value adaptiveArmourLimit in the top level ship classes, if Zero the ship has no adaptive armour.  A simple check for each ship while building its data window should add to much overhead.  We need the value anyway as we need to know how many points of adaptive armour a ship can have.

**Comment by AncientSion** [comment]
Is your last paragraph missing a "not" (overhead) ?


I can do the interface (javascript) easily.

How do you plan to solve the issue where "valid" choices to adapt yourself to are only damagestypes you have suffered yet (that is rule, isnt it) ?

**Comment by tksolway** [comment]
It is the rule, I haven't quite figured that out just yet.  Easiest way would likely be a second array that gets incremented by the DoDamage function.  That array will need to initialized by the constructor with the initial assignment limit as its initial value.  As most ships can have at least some of their Adaptive armour assigned at the start of battle.  I'll have to check the rules again, but I don't think you can change adaptive armour after it's been set.  Controlling that would likely fall to an interface check?

**Comment by tksolway** [comment]
The initial assignment of armour should happen during deployment as you get to see your opponent's fleet, but after that armour should be assigned.  Then we would have to Zero out that check array (other than assigned values) to ensure that it can be checked for the limit.  It'll take me a bit to develop a procedure for this.  Probably not todya :-)

**Comment by AncientSion** [comment]
I wouldnt suggest to put the adaptive armour setup to deployment. Use initial orders, its better for gameflow as well as managing it code-wise.
What i would do is put a hook into each ship that has the general $adaptiveArmour trait. If a weapon hits such a ship, check for
if ($target->adaptiveArmour){
   do something which, in the end *absolutly* must be put into a new database table
}

its important to realize that whenever a game loads (like when you do your moves), the game readies a BLANK instance of ship using the class constructor. So you have a ship, with a bunch of systems. But this ship has soul as of yet, its just a static instance.
After all ships have been generated, DBManager.php populates ! these ships.
Every fireorder, every "step" of moving, every critical, every damageentry (for each shot) (!) is put into each system of each ship whenver a game is loaded.

Maybe you know this, for me it took me some to realize that the ship classes are basicly modified via the database upon every single load of a game.

**Comment by tksolway** [comment]
Ah, ok, here I was thinking that the classes were kept active.  The arrays I've setup won't be of any use then, we'll need something that will be sent to the DB

**Comment by AncientSion** [comment]
The arrays by themselves are good, if they are initialized (with keys, without values) using the constructor __function
it just that the contents of this array (aka the keys) need to be filled with values from the DB. 
The array should have one key for each possible damage type, and the value of that key should be 0 on construction. If that type of damage was received and hence is legit to adapt to, the value should become 1 - using mySQL.

i.e. 
  class Ship 
  public $receivedDamageTypes = [
  "Pulse" => 0,
  "Gravitic" => 0
]

and so on. 

Then, exactly like DBManager "fills" the blank instance of this ship's systems ($ship->systems array) is filled with damage and criticals, our $receivedDamageTypes array would received altered VALUEs (0 or 1).

I think your/the idea is good by itself.

**Comment by Aatu** [comment]
More efficient for the array to be empty at initialization, and then you just add new key/value pairs when needed. If you don't find a certain key from the array, you can consider it to be 0.

**Comment by Aatu** [comment]
Btw, I made tksolway a collaborator. He now has push permissions to this repo too.

**Comment by tksolway** [comment]
Thanks Aatu.

Chris, I added another array called releasedAdaptiveArmour specifically for that.  If we can add these five values to the DB and have them propagated during construction it should work as it is.  I'll have to take a look at the DBManager and see how it's working.  

I'll be adding a different pull request so you can see the new alterations, I redid them on the main fork.

**Comment by AncientSion** [comment]
there is a table.php file in the repo. I used this to create a new table for my flightsize' feature.
You can alter the table.php file to create a tac_adaptivesettings table with the columns you need (8?).
If the file is on the server, trying to access the file will trigger the script and create the table.

then, use DBManager.php to read and write from that table.
Look for "tac_flightsize" as an example. That function controls how many "flights" are added to fighter-class object.

**Comment by AncientSion** [comment]
I have worked a bit on this feature.
In initial orders, a ship with $adaptiveArmour = true attribute will spawn a button in the shipwindow.
Upon clicking the button, ajaxinterface will transfer the ship-id to PHP.
From there a client handler can use the database and return an object array to the client - prefereblly an array of strings that contains the valid damage types like suggested above.

The client will then construct a small GUI-ish pulldown stuff thingy and populate it using the return object array. A player can then select how to distribute his armour settings.
The whole "distribute his armour settings" thing is pretty complicated from an how-should-the-interface-look though.

Once a player has made his choices, another ajax request can put the player's picks to the server and write it into the DB for use in that turns fire order (also need to make sure the chosen settings are visible while movement to the hostile player).


currently done: 
- alter shipwindow to show button if valid in intial orders
- transfer ship id to server
- return function back to client (omitting data atm, waiting for proper php function to link to).

**Comment by AncientSion** [comment]
So i went the extra mile.
table is created, entries (gameId, shipId, damageTypes with value INT are written when a ship is bought that uses adaptive armour.
when a game is loaded, a ship with adaptiveArmour will be altered according to the data in the table.

The client now has a ship with an array of damageTypes and this can be used to create the GUI on clicking the button mentioned above.
Basicly, i think this feature is on a very good way.

Missing
 server
- alter "getArmor()" to account for additional armor
- when writing damages into the table (after fire), check for a ship with adaptiveArmour. If so, loop over the systems/fireorders and UPDATE the formerly created row.

client
create a menu with a shit ton of menus and logics so a player can his armour stuff.
use ajax to push ther stuff to the server so its there when damage resolves.

**Comment by tksolway** [comment]
Wow man, that's a lot of work.  It was a long weekend here in Canada so I wasn't paying much attention :-).I believe my branch does have an addition to getArmour that should work.  I'll take a look at what you've done and see if it still works the way I think it should.  Not sure if I can get to it today though, looks to be a busy day at work

**Comment by AncientSion** [comment]
Dont worry about it.
I will ready the feature, perhaps by the weekend. Ill also include parts of your open pullrequest.

I have tagged you on FB for a minor bugfix in regards to shield generators :p

**Comment by tksolway** [comment]
Ya, I'll work on the shields

**Comment by tksolway** [comment]
Hey Chris, can you post your current code for the Adaptive Armour I'd love to see where in the code all these changes are being made, it will give me a better idea how things are working.  Please just make a pull request on your current branch so I can see all the changes.
