### ISSUE TITLE
Usuuth and Cascor

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#663]
Usuuth and Cascor are factions that don't need all that many new systems, and Tom decided to make them playable.

I help with more complicated systems. 

This thread I am creating as kind of communications thread :) .

**Comment by Zero1627** [comment]
First things to communicate:
 - I've created Particle Hammer icon and fitted it to weapon.
 - I plan to introduce MicroOSATs soon, that will be usefull for Usuuth as well.

**Comment by Zero1627** [comment]
...and I found Burst Torpedo looking over Usuuth :) . Not a priority weapon though.

**Comment by tksolway** [comment]
I assume you're referring to the Sweqall Assault Cruiser, it's not an official ship.  All of the official ships for the Usuuth are now done.  I just need to get the images done, which for me is the hard part.

**Comment by tksolway** [comment]
Thanks for the icon, As I said, I think the Avenger images is fine for the Serron ships as they are basically just a wedge, I'll try coming up with something for the other two ships.

**Comment by Zero1627** [comment]
>All of the official ships for the Usuuth are now done.

Indeed I haven't checked status of expansion this came up with. Suspected this may be the case though, as it's showtime unit by ISD - and Orieni (and their subjects) didn't get many official units past WoCR.

Will do Cascor weapons when time allows.

**Comment by tksolway** [comment]
The Usuuth are confusing, because they guy that did these unofficial ones left the S8 on the sheet, so it looks like it comes from Showdowns 8.  but the book itself doesn't mention them at all.

**Comment by Zero1627** [comment]
Yes, when  looking over the units I just see them as "S8" which suggests they're official...

Still they would be nice to have, perhaps marked as custom.

**Comment by Zero1627** [comment]
I have started on Cascor weapons, hope to have them completed by Tuesday (I see You haven't started on them yet). Please don't start on them as well, so we don't overlap ;) .

When weapons are ready You might consider scratching and re-starting Cascor branch, just to have it include weapons and be actually possible to test before merging into master.

**Comment by tksolway** [comment]
No worries, I doubt I’ll have time to work on them this weekend.

**Comment by Zero1627** [comment]
Cascor weapons are ready to be used.

Compared to officiaI performance I have modified Ion Field Generator a bit:
 - no effects on current turn (as Ballistics do not impact before gunfire), all effects are on next turn.
 - weapon charge resed was strengthened to forced shutdown for a turn (as this was similar and already existing effect - far easier to achieve).

New weapon classes (all ship weapons can be called with 0 as structure and power for default values):
RadCannon
IonFieldGenerator
IonicLaser
DualIonBolter
Ionizer

**Tom** - You may create Cascor ships now. I suggest dropping existing Cascor branch and creating a new one from master, just so compiling and testing ships doesn't require merging into master first.

**Wolfgang** - if You could create Cascor graphics it would make them far more distinct than re-used images...

...and I will create icons for these new weapons (will be ready before public deployment).

**Comment by tksolway** [comment]
Thanks Marcin,

I’ll get started on the ships this week.

**Comment by Zero1627** [comment]
I have Cascor compiled, fixed a few details that were visible on a glance (like Tinquicc aft gun being forward mounted and forward firing ;) ).
All ships and bases seem to work, I have deployed them for test.
Fighters have some problem still (are pickable but deploying them crashes the game). I suspect some minor/typo problem, but am too tired to finish this today - if time permits will finish and deploy this tomorrow.

**Comment by Zero1627** [comment]
Deployed.

I see some minor things to be fixed (encountering them live, using something gives much better pictura than looking at code definition) - am making fixes in my branch, will deploy once fixes are reasonably complete.
...teething problems, natural for any new creation.

**Comment by Zero1627** [comment]
Tom, sides are supposed to be symmetrical usually ;) . Only now noted this.

**Comment by Zero1627** [comment]
I am closing this issue - both Cascor and Usuuth are deployed and seem to be working fine, on a glance at least. Fixes will be later applied as needed.
