### ISSUE TITLE
Anti-fighter fire allocation

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#672]
Anti-fighter hits are allocated randomly between remaining craft, which is a serious difference from standard player decision.

Sensible allocation is not possible because actual damage (and effects) are considered far after picking target system (fighter, in this case).

But it occured to me that semi-sensible allocation is possible, using estimated values - a bit like section choice is done. It would even be possible to include armor-piercing/enhancing effects, by calling appropriate getArmour() method for every fighter (fireOrder is available, so actual weapon firing can be passed - and so specials used).

It would work on estimated instead of real values, but... with sensible algorithm that would be a real enhancement.

**Comment by Zero1627** [comment]
A sketch of algorithm to be used.

Values needed:
 - minimum and maximum damage (including effect of armor) (let's assume damage spread is linear - for most light weapons that's even true)
 - whether a fighter is already subject of dropout roll
 - chance of outright destruction by hit
 - chance of becoming subject of dropout (no need to estimate dropout chance, more chance of being subject automatically means deeper dropout as well)

Priorities of allocation:
 - no chance of dropout nor destruction
 - least chance of getting into dropout (let's prefer instant destruction of a fighter over getting dropout chance on two of them, that'll lead to less losses overall)
 - least chance of being destroyed
 - being most damaged (if there's no chance of damage causing immediate effect, it's better to pick already damaged fighter in case of some special effect)
 - last fighter in flight (if some fighter is more important than the others it'll be the first one)

**Comment by Zero1627** [comment]
Actually calculating chances is not needed: more damaged fighter will have higher chance of being dropped out and destroyed. So only information whether forcing dropout or outright destruction is possible is necessary.
And algorithm would look like:
 - no chance of forcing dropout
 - no chance of being destroyed
 - being more damaged
 - having higher ID

**Comment by tksolway** [comment]
A simpler solution to this may be to just randomly target as normal, unless there is a fighter with four of less hitpoints left (that has damage in the case of fighters with less than 10).  Those fighters have a 50+% chance of drop out already, so choose them as the target.  Otherwise, just assign automatically.

You could do a simple while loop on the fighters in the flight, if you find one with a 50+% chance of drop out, target it, otherwise move on to normal targeting priority.

**Comment by Zero1627** [comment]
If I do it, I'll try to do it the best way I can. Always estimating seems better option. Work necessary isn't really all that different - problem was defining algorithm which uses data available to reasonably sensible result (done now), not implementing it once found.

**Comment by Zero1627** [comment]
done, works!
...now make AF firing order sensible as well :)
