### ISSUE TITLE
3-sided base

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#708]
Some official starbases are 3-sided. There is no appropriate template in game, but I expect it to be easily achievable based on SmallBase template (or 6-sided base template, now that I think about it...).

**Comment by melkorium** [comment]
I've already drafted up some code for a 3-sided base in preparation for adding the Chlonas starbase.  Will add this when I add the base in next week or so (just drawing it atm)!

**Comment by Zero1627** [comment]
done (mostly by Melkorium) -as SmallStarbaseThreeSections!
