### ISSUE TITLE
Request: Hex grid

### ISSUE THREAD

**Issue by SebastianSeiml** [Aatu/FieryVoid#71]
I want to advocate a hex grid, which is also shown at higher zoom levels. Currently I see only the hex grid with a detail of ~ 15 hexes.
As (IMHO) the hex grid is important for maneuvering (e.g. centerline), evading weapon arcs and quick counting of a mevement path it would be preferabe to see the grid also for a detail of ~ 30 hexes (or even more).

Of course, the best solution would be if the hex grid would be available at every zoom level, but each player could activate or deactivate it at will.

**Comment by tksolway** [comment]
I believe this has been successfully implemented, I will close this ticket.

**Comment by tksolway** [comment]
Never mind, I require elevated access for that :-).
