### ISSUE TITLE
Mass Driver hit chance calculation

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#937]
in front end weapon hit chance is not calculated properly because conditions like speed 0 and Enormous size requirement are highly non-standard.

But now Packet Torpedo has paved way for non-standard calculations - perhaps appropriate routine coulb ebe added for Mass Driver? It wouldn't need to be exact, just assuring that playe ris informed of automatic miss...

**Comment by melkorium** [comment]
This is now completed :)  Conditional check for Mass Driver etc added to calculateHitChange() in weaponManager.js
