### ISSUE TITLE
ships.js too large

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#982]
Apparently ships.js file has grown too large and drawn attention of intermediate cache servers, which causes trouble during updates.

Proposed solution: split to separate faction files? (both in how the cache is used and how it's generated in the first place )

**Comment by tksolway** [comment]
There may be a header code you can use to tell the cache servers to ignore the file/site.  I’m afraid I don’t know what it would be though.

This is a hack using a timestamp that should work in the meantime
https://stackoverflow.com/questions/4206224/better-way-to-prevent-browser-caching-of-javascript-files

**Comment by tksolway** [comment]
Ah, found a comment related to the header

Caching is your friend. If browsers are caching these files incorrectly, it means something is wrong with the HTTP headers your web server is sending along with the JS and CSS files themselves (not the HTML page that uses them). The browser uses those headers to figure out if it can cache the file.
Your Web server can send these headers (on every JS and CSS file it serves) to tell browsers not to cache them:
Cache-Control: no-cache
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
But that will increase the network load on your site, and users will see the page load slower. You could be a little more lenient and allow the browser to cache the CSS file for 60 seconds:
Cache-Control: max-age=60
If you really want the browser to check for a new file with every single page load, you can still save some network traffic by using an ETag:
Cache-Control: max-age=0
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
ETag: "o2389r-98ur0-w3894tu-q894"
The ETag is simply a unique identifier your Web server makes up each time the file changes. The next time the browser wants the file, it asks the server, "does /js/pm.init.js still have the ETag o2389r98ur0w3894tuq894?" and if so, your server simply says, "yes". That way your server doesn't have to send the whole file again, and the user doesn't have to wait for it to load. Win-win.
How to convince your web server to autogenerate ETags depends on the server. It's usually not hard.
I've seen the hack you're using before. Like so much on the Web, it's not pretty or particularly efficient, but it works.

**Comment by Zero1627** [comment]
sadly that's the core of problem - I WANT the file cached, it's the only purpose of this file's existence - if it's not cached then it might as well not exist.

Problem comes with new version of the file - how can refresh be forced? In browser that's simple (ctrl+F5), but I do not know a way to force intermediate servers to check for new version... (if the diagnosis of intermediate servers is correct in the first place of course).

**Comment by Zero1627** [comment]
note to self:
ships.js structure is simple instruction: window.staticShips = (list of ships).

So, in theory, it could contain just variable definition, and further related files could ADD to it (instead of defining it). Or even be flexible and base ships.js would not be needed.

Additional files would have to be added where ships.js currently is, and creation script would have to be modified appropriately.

Units could be split by faction or maybe just new file generated after predefined number of ships?...

**Comment by tksolway** [comment]
If that’s the case, then including a build number in the file should force the cache to update for each new version.

**Comment by Zero1627** [comment]
cache refit ready, will need some more testing before deployment.

**Comment by Zero1627** [comment]
testet, polished, works :)
