### ISSUE TITLE
Ipsha weapons

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#994]
make intercept-capable Ipsha weapons suffer cooldown on defensive fire! (EM Pulsar only, I guess)

**Comment by tksolway** [comment]
Would they have to be manually fired in intercept mode then?  They are still a one turn weapon right?

**Comment by Zero1627** [comment]
> Would they have to be manually fired in intercept mode then?  They are still a one turn weapon right?
All Ipsha weapons are technically one-turn. 
Whether they should be manually turned into interception mode... Possibly yes. OTOH Brakiri Pulsars are not (exact same effect when boosted). And it would be a bother. So I'm thinking no - and intend on leaving them on auto-intercept. 

Nothing is set in stone though, I can change that without much fuss (turn it into accelertator weapon with 2 turns arming, but able to fire at full power after turn 1).

**Comment by Zero1627** [comment]
done, to be tested.

**Comment by Zero1627** [comment]
confirmed, works
